<?php
$title = $this->config['component']['output_inventory'][0];
$action = $this->config['action']['create']['text'];
echo $this->layoutHelper()->header(array(
	'module' => array('url' => $this->url('process/output_inventory'),'value' => $title),
	'action' => array('url' => '','value' => $action)
	));
	?>
	<?php $form = $this->form; ?>
	<?php $form->setAttribute('action', $this->url('process/output_inventory', array('action' => 'add'))); ?>
	<?php $form->prepare(); ?>
	<?php echo $this->form()->openTag($form); ?>
	<?php echo $this->formHidden($form->get('id')); ?>
	<?php echo $this->formHidden($form->get('csrf')); ?>
	<div class="form-group">
		<?php echo $this->formLabel($form->get('register_date')->setLabel($this->config['component']['register_date'][1])); ?>
		<div class="col-sm-2">
			<?php echo $this->formInput($form->get('register_date')); ?>
			<?php echo $this->formElementErrors($form->get('register_date'), array("class" => "error")); ?>
		</div>
	</div>
	<div class="form-group">
		<?php echo $this->formLabel($form->get('client')->setLabel($this->config['component']['client'][1])); ?>
		<div class="col-sm-4">
			<?php echo $this->formSelect($form->get('client')); ?>
			<?php echo $this->formElementErrors($form->get('client'), array("class" => "error")); ?>
		</div>
</div>
<div class="form-group">
	<?php echo $this->formLabel($form->get('payment_method')->setLabel($this->config['component']['payment_method'][1])); ?>
	<div class="col-sm-4">
		<?php echo $this->formSelect($form->get('payment_method')); ?>
		<?php echo $this->formElementErrors($form->get('payment_method'), array("class" => "error")); ?>
	</div>
</div>
<div class="form-group">
	<?php echo $this->formLabel($form->get('seller')->setLabel($this->config['component']['seller'][1])); ?>
	<div class="col-sm-4">
		<?php echo $this->formSelect($form->get('seller')); ?>
		<?php echo $this->formElementErrors($form->get('seller'), array("class" => "error")); ?>
	</div>
</div>
<div class="form-group">
	<?php echo $this->formLabel($form->get('guide_number')->setLabel($this->config['component']['guide_number'][1])); ?>
	<div class="col-sm-2">
		<?php echo $this->formInput($form->get('guide_number')); ?>
		<?php echo $this->formElementErrors($form->get('guide_number'), array("class" => "error")); ?>
	</div>
</div>
<div class="form-group">
	<?php echo $this->formLabel($form->get('observation')->setLabel($this->config['component']['observation'][1])); ?>
	<div class="col-sm-6">
		<?php echo $this->formTextarea($form->get('observation')); ?>
		<?php echo $this->formElementErrors($form->get('observation'), array("class" => "error")); ?>
	</div>
</div>
<div class="well well-sm">
	<?php echo $this->formSubmit($form->get('submit')->setValue($this->config['action']['detail']['text'])); ?>
</div>
<?php echo $this->form()->closeTag(); ?>
