<?php
$this->headScript()->prependFile('/js/details-output-inventory.js', 'text/javascript');

$title1 = $this->config['component']['output_inventory'][0];
$title2 = $this->config['component']['detail_output_inventory'][0];
$action = $this->config['action']['detail']['text'];
echo $this->layoutHelper()->header(array(
	'module' => array('url' => $this->url('process/output_inventory/add'),'value' => $title1),
	'action' => array('url' => $this->url('process/output_inventory/add/details'),'value' => $title2)
	));
	?>
	<div class="form-group">
		<div class="col-sm-12">
			<div class="panel panel-default">
				<div class="panel-heading"></div>
				<table class="table table-bordered">
					<thead>
						<tr>
							<th><?php echo $config['component']['number'][1]; ?></th>
							<th><?php echo $config['component']['client'][1]; ?></th>
							<th><?php echo $config['component']['seller'][1]; ?></th>
							<th><?php echo $config['component']['payment_method'][1]; ?></th>
							<th><?php echo $config['component']['guide_number'][1]; ?></th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td><b><?php echo $outputInventory->getId(); ?></b></td>
							<td><?php echo $outputInventory->getClientFirstName()." ".$outputInventory->getClientLastName(); ?></td>
							<td><?php echo $outputInventory->getPaymentMethodName(); ?></td>
							<td><?php echo $outputInventory->getSellerFirstName()." ".$outputInventory->getSellerLastName(); ?></td>
							<td><?php echo $outputInventory->getGuideNumber(); ?></td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
	</div>
	<div class='clearfix'></div>
	<?php $form = $this->form; ?>
	<?php $form->setAttribute('action', $this->url('process/output_inventory/add/details', array('action' => 'add'))); ?>
	<?php $form->prepare(); ?>
	<?php echo $this->form()->openTag($form); ?>
	<?php echo $this->formHidden($form->get('csrf')); ?>
	<div class="form-group">
		<?php echo $this->formLabel($form->get('qty')->setLabel($this->config['component']['qty'][1])); ?>
		<div class="col-sm-2">
			<?php echo $this->formInput($form->get('qty')); ?>
			<?php echo $this->formElementErrors($form->get('qty'), array("class" => "error")); ?>
		</div>
	</div>
	<div class="form-group">
		<?php echo $this->formLabel($form->get('cost')->setLabel($this->config['component']['cost'][1])); ?>
		<div class="col-sm-3">
			<div class="input-group">
				<span class="input-group-addon">$</span>
				<?php echo $this->formInput($form->get('cost')); ?>
				<span class="input-group-addon">.00</span>
			</div>

			<?php echo $this->formElementErrors($form->get('cost'), array("class" => "error")); ?>
		</div>
	</div>
	<div class="form-group">
		<?php echo $this->formLabel($form->get('iva')->setLabel($this->config['component']['iva'][1])); ?>
		<div class="col-sm-3">
			<?php echo $this->formSelect($form->get('iva')); ?>
			<?php echo $this->formElementErrors($form->get('iva'), array("class" => "error")); ?>
		</div>
	</div>
	<div class="form-group">
		<?php echo $this->formLabel($form->get('product_serial')->setLabel($this->config['component']['product'][1]." ".$this->config['component']['serial_name'][1])); ?>
		<div class="col-sm-4">
			<?php echo $this->formInput($form->get('product_serial')); ?>
			<ul class="serial-result" id='serials'>
			</ul>
			<?php echo $this->formSelect($form->get('product')); ?>
			<?php echo $this->formElementErrors($form->get('product'), array("class" => "error")); ?>
		</div>
	</div>
	<?php echo $this->formSubmit($form->get('submit')->setValue($this->config['action']['add']['text'])); ?>
	<?php echo $this->form()->closeTag(); ?>
	<br>
	<?php if(isset($detailsOutputInventory) && count($detailsOutputInventory)>0): ?>
		<div class="panel panel-default">
			<div class="panel-heading"><h5><?php echo $title2; ?></h5></div>
			<table class="table table-bordered table-hover">
				<thead>
					<tr>
						<th><?php echo $config['component']['cost'][1]; ?></th>
						<th><?php echo $config['component']['iva'][1]; ?></th>
						<th><?php echo $config['component']['product'][1]; ?></th>
						<th><?php echo $config['component']['serial_name'][1]; ?></th>
						<th><?php echo $config['component']['qty'][1]; ?></th>
						<th><?php echo $config['component']['total'][1]; ?></th>
						<th></th>
					</tr>
				</thead>
				<?php 
				$totalQty = 0 ; 
				$totalIva = 0 ;
				$totalCost = 0 ;

				foreach($detailsOutputInventory as $detailOutputInventory): ?>
				<?php dumpx($detailOutputInventory); ?>
				<?php $subTotalCost = 0 ?>
				<tbody>
					<tr>
						<td>$ <?php echo number_format($detailOutputInventory->getCost()); ?></td>
						<td>$ 
							<?php 
							$totalIva = $totalIva + $detailOutputInventory->getIvaAccumulated();
							echo number_format($detailOutputInventory->getIvaAccumulated()); 
							?>
						</td>
						<td>
							<a href="javascript:void(0);" class="tooltip_preview" data-original-title="<?php echo $detailOutputInventory->getProduct(); ?>"><?php echo substr($detailOutputInventory->getProduct(),0,30); ?>...</a>
						</td>
						<td>serial</td>
						<td>
							<?php 
							$totalQty = $totalQty +	$detailOutputInventory->getQty(); 
							echo $detailOutputInventory->getQty();
							?>
						</td>
						<td>$ 
							<?php 
							$subTotalCost = $detailOutputInventory->getQty() * $detailOutputInventory->getCost() ;
							echo number_format($subTotalCost); 
							$totalCost = $totalCost + $subTotalCost;
							?>
						</td>
						<td>
							<a href="<?php echo $this->url('process/receive_inventory/add/details/delete', array('id' => $detailOutputInventory->getId())); ?>">
								<label class="<?php echo $this->config['action']['delete']['class']; ?>">
									<i class="<?php echo $this->config['action']['delete']['icon'] ; ?>"></i>
								</label>
							</a>
						</td>
					</tr>
				</tbody>
				<?php $totalCost = $totalCost + $detailOutputInventory->getCost(); ?>
			<?php endforeach; ?>
			<tfoot>
				<tr class="success">
					<td></td>
					<td>$ <?php echo number_format($totalIva) ; ?></td>
					<td></td>
					<td></td>
					<td><?php echo $totalQty ; ?></td>
					<td>$ <?php echo number_format($totalCost); ?></td>
					<td>$ <?php echo number_format($totalIva + $totalCost) ; ?></td>
				</tr>
			</tfoot>
		</table>
	</div>
<?php endif; ?>