<?php
$this->headScript()->prependFile('/js/details-output-inventory.js', 'text/javascript');

$title1 = $this->config['component']['output_inventory'][0];
$title2 = $this->config['component']['detail_output_inventory'][0];
$action = $this->config['action']['detail']['text'];
echo $this->layoutHelper()->header(array(
	'module' => array('url' => $this->url('process/output_inventory/add'),'value' => $title1),
	'action' => array('url' => $this->url('process/output_inventory/add/details'),'value' => $title2)
	));
	?>
	<div class="form-group">
		<div class="col-sm-12">
			<div class="panel panel-default">
				<div class="panel-heading"></div>
				<table class="table table-bordered">
					<thead>
						<tr>
							<th><?php echo $config['component']['number'][1]; ?></th>
							<th><?php echo $config['component']['client'][1]; ?></th>
							<th><?php echo $config['component']['seller'][1]; ?></th>
							<th><?php echo $config['component']['payment_method'][1]; ?></th>
							<th><?php echo $config['component']['guide_number'][1]; ?></th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td><b><?php echo $outputInventory->getId(); ?></b></td>
							<td><?php echo $outputInventory->getClientFirstName()." ".$outputInventory->getClientLastName(); ?></td>
							<td><?php echo $outputInventory->getPaymentMethodName(); ?></td>
							<td><?php echo $outputInventory->getSellerFirstName()." ".$outputInventory->getSellerLastName(); ?></td>
							<td><?php echo $outputInventory->getGuideNumber(); ?></td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
	</div>
	<div class='clearfix'></div>
	<?php $form = $this->form; ?>
	<?php $form->setAttribute('action', $this->url('process/output_inventory/add/details', array('action' => 'add'))); ?>
	<?php $form->prepare(); ?>
	<?php echo $this->form()->openTag($form); ?>
	<?php echo $this->formHidden($form->get('csrf')); ?>
	<div class="form-group">
		<?php echo $this->formLabel($form->get('qty')->setLabel($this->config['component']['qty'][1])); ?>
		<div class="col-sm-2">
			<?php echo $this->formInput($form->get('qty')); ?>
			<?php echo $this->formElementErrors($form->get('qty'), array("class" => "error")); ?>
		</div>
	</div>
	<div class="form-group">
		<?php echo $this->formLabel($form->get('sale_value')->setLabel($this->config['component']['sale_value'][1])); ?>
		<div class="col-sm-3">
			<div class="input-group">
				<span class="input-group-addon">$</span>
				<?php echo $this->formInput($form->get('sale_value')); ?>
				<span class="input-group-addon">.00</span>
			</div>

			<?php echo $this->formElementErrors($form->get('sale_value'), array("class" => "error")); ?>
		</div>
	</div>
	<div class="form-group">
		<?php echo $this->formLabel($form->get('iva')->setLabel($this->config['component']['iva'][1])); ?>
		<div class="col-sm-3">
			<?php echo $this->formSelect($form->get('iva')); ?>
			<?php echo $this->formElementErrors($form->get('iva'), array("class" => "error")); ?>
		</div>
	</div>
	<div class="form-group">
		<?php echo $this->formLabel($form->get('product_serial')->setLabel($this->config['component']['product'][1]." ".$this->config['component']['serial_name'][1])); ?>
		<div class="col-sm-4">
			<?php echo $this->formInput($form->get('product_serial')); ?>
			<ul class="serial-result" id='serials'>
			</ul>
			<?php echo $this->formSelect($form->get('product')); ?>
			<?php echo $this->formElementErrors($form->get('product'), array("class" => "error")); ?>
		</div>
	</div>
	<?php echo $this->formSubmit($form->get('submit')->setValue($this->config['action']['add']['text'])); ?>
	<?php echo $this->form()->closeTag(); ?>
	<br>