<?php
$title = $this->config['component']['brand'][0];
$action = $this->config['action']['new'];
echo $this->layoutHelper()->header(array(
	'module' => array('url' => $this->url('admin/brand'),'value' => $title),
	'action' => array('url' => '','value' => $action)
	));
	?>
	<?php $form = $this->form; ?>
	<?php $form->setAttribute('action', $this->url('admin/brand', array('action' => 'add'))); ?>
	<?php $form->prepare(); ?>
	<?php echo $this->form()->openTag($form); ?>
	<?php echo $this->formHidden($form->get('id')); ?>
	<?php echo $this->formHidden($form->get('csrf')); ?>
	<div class="form-group">
		<?php echo $this->formLabel($form->get('name')->setLabel($this->config['component']['name'][1])); ?>
		<div class="col-sm-4">
			<?php echo $this->formInput($form->get('name')); ?>
			<?php echo $this->formElementErrors($form->get('name'), array("class" => "error")); ?>
		</div>
	</div>
	<div class="form-group">
		<?php echo $this->formLabel($form->get('image')->setLabel($this->config['component']['image'][1])); ?>
		<div class="col-sm-4">
			<?php echo $this->formInput($form->get('image')); ?>
			<?php echo $this->formElementErrors($form->get('image'), array("class" => "error")); ?>
			<p class="help-block">
				Extensiones Permitidas: <?php echo implode($this->config['file_characteristics']['image']['extension'],',') ;?><br>
				Tama&ntilde;o: 
				<?php foreach($this->config['file_characteristics']['image']['size'] as $range => $size): ?>
					<?php echo $range." ".$size ; ?>
				<?php endforeach; ?>
			</p>
		</div>
	</div>
	<div class="form-group">
		<?php echo $this->formLabel($form->get('background_image')->setLabel($this->config['component']['background_image'][1])); ?>
		<div class="col-sm-4">
			<?php echo $this->formInput($form->get('background_image')); ?>
			<?php echo $this->formElementErrors($form->get('background_image'), array("class" => "error")); ?>
			<div class="clearfix"></div>
			<p class="help-block">
				Extensiones Permitidas: <?php echo implode($this->config['file_characteristics']['image']['extension'],',') ;?><br>
				Tama&ntilde;o: 
				<?php foreach($this->config['file_characteristics']['image']['size'] as $range => $size): ?>
					<?php echo $range." ".$size ; ?>
				<?php endforeach; ?>
			</p>
		</div>
	</div>
	<div class="form-group">
		<?php echo $this->formLabel($form->get('description')->setLabel($this->config['component']['description'][1])); ?>
		<div class="col-sm-6">
			<?php echo $this->formTextarea($form->get('description')); ?>
			<?php echo $this->formElementErrors($form->get('description'), array("class" => "error")); ?>

		</div>
	</div>
	<div class="well well-sm">
		<?php echo $this->formSubmit($form->get('submit')->setValue($this->config['action']['create'])); ?>
		&nbsp;
		<a href="<?php echo $this->url('admin/brand'); ?>"><?php echo $this->config['action']['return'] ; ?> </a>
	</div>
	<?php echo $this->form()->closeTag(); ?>