<?php
$title = $this->config['component']['brand'][0];
$this->headTitle($title);
?>
<h2 class="page-header"><?php echo $title ; ?></h2>
<?php $form = $this->form; ?>
<?php $form->setAttribute('action', $this->url('admin/brand', array( 'action' => 'edit', 'id' => $this->id)));
?>
<?php $form->prepare(); ?>
<?php echo $this->form()->openTag($form); ?>
<?php echo $this->formHidden($form->get('id')); ?>
<?php echo $this->formHidden($form->get('csrf')); ?>

<div class="form-group">
	<?php echo $this->formLabel($form->get('name')->setLabel($this->config['component']['name'][1])); ?>
	<div class="col-sm-4">
		<?php echo $this->formInput($form->get('name')); ?>
		<?php echo $this->formElementErrors($form->get('name'), array("class" => "error")); ?>
	</div>
</div>

<div class="form-group">
	<?php echo $this->formLabel($form->get('image')->setLabel($this->config['component']['image'][1])); ?>
	<div class="col-sm-4">
		<?php if($image): ?>
			<a href="javascript:void(0)" class="btn btn-primary btn-xs" onclick="showModalImage('/images/brand/<?php echo $image; ?>','<?php echo $this->config['component']['image'][1] ; ?>')">
				<span class="glyphicon glyphicon-search"></span>
			</a>
		<?php endif; ?>
		<div class='pull-left'>
		<?php echo $this->formInput($form->get('image')); ?>
		<?php echo $this->formElementErrors($form->get('image'), array("class" => "error")); ?>
		</div>
		<p class="help-block">
			Extensiones Permitidas: <?php echo implode($this->config['file_characteristics']['image']['extension'],',') ;?><br>
			Tama&ntilde;o:
			<?php foreach($this->config['file_characteristics']['image']['size'] as $range => $size): ?>
				<?php echo $range." ".$size ; ?>
			<?php endforeach; ?>
		</p>
	</div>
</div>
<div class="form-group">
	<?php echo $this->formLabel($form->get('background_image')->setLabel($this->config['component']['background_image'][1])); ?>
	<div class="col-sm-4">
		<?php if($backgroundImage): ?>
			<a href="javascript:void(0)" class="btn btn-primary btn-xs" onclick="showModalImage('/images/brand/<?php echo $backgroundImage; ?>','<?php echo $this->config['component']['background_image'][1] ; ?>')">
				<span class="glyphicon glyphicon-search"></span>
			</a>
		<?php endif; ?>
		<div class='pull-left'>
		<?php echo $this->formInput($form->get('background_image')); ?>
		<?php echo $this->formElementErrors($form->get('background_image'), array("class" => "error")); ?>
		</div>
		<p class="help-block">
			Extensiones Permitidas: <?php echo implode($this->config['file_characteristics']['image']['extension'],',') ;?><br>
			Tama&ntilde;o: 
			<?php foreach($this->config['file_characteristics']['image']['size'] as $range => $size): ?>
				<?php echo $range." ".$size ; ?>
			<?php endforeach; ?>
		</p>
	</div>
</div>

<div class="form-group">
	<?php echo $this->formLabel($form->get('description')->setLabel($this->config['component']['description'][1])); ?>
	<div class="col-sm-4">
		<?php echo $this->formTextarea($form->get('description')); ?>
		<?php echo $this->formElementErrors($form->get('description'), array("class" => "error")); ?>
	</div>
</div>
<?php echo $this->formSubmit($form->get('submit')->setValue($this->config['action']['update']['text'])); ?>
&nbsp;
<a href="<?php echo $this->url('admin/brand'); ?>"><label class="<?php echo $this->config['action']['return']['class']; ?>">
<i class="<?php echo $this->config['action']['return']['icon'] ; ?>"></i>
<?php echo $this->config['action']['return']['text']; ?>
</label> </a>
<?php echo $this->form()->closeTag(); ?>
<?php echo $this->modalHelper()->image(); ?>