<?php
$title = $this->config['component']['brand'][0];
$this->headTitle($title);
?>
<h2><?php echo $this->escapeHtml($title); ?></h2>
<p>
    <a href="<?php echo $this->url('brand', array('action'=>'add'));?>"><?php echo $this->config['action']['add'] ; ?></a>
</p>

<table class="table table-striped table-bordered">
<tr>
    <th><?php echo $this->config['component']['name'][1] ;?></th>
    <th><?php echo $this->config['component']['description'][1] ;?></th>
    <th><?php echo $this->config['component']['image'][1] ;?></th>
    <th><?php echo $this->config['component']['background_image'][1] ;?></th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($brands as $brand) : ?>
<tr>
    <td><?php echo $this->escapeHtml($brand->getName());?></td>
    <td><?php echo $this->escapeHtml($brand->getDescription());?></td>
    <td class='column-button'>
        <?php if($brand->getImage()): ?>
            <a href="javascript:void(0)" class="btn btn-default" onclick="showModal('images/brand/<?php echo $brand->getImage() ?>','<?php echo $this->config['component']['image'][1] ; ?>')"><span class="glyphicon glyphicon-search"></span></a>
        <?php endif; ?>
    </td>
    <td class='column-button'>
        <?php if($brand->getBackgroundImage()): ?>
            <a href="javascript:void(0)" class="btn btn-default" onclick="showModal('images/brand/<?php echo $brand->getBackgroundImage() ?>','<?php echo $this->config['component']['background_image'][1] ; ?>')"><span class="glyphicon glyphicon-search"></span></a>
        <?php endif; ?>
    </td>
    <td class='column-button'>
        <a href="<?php echo $this->url('brand', array('action'=>'edit', 'id' => $brand->getId())); ?>"><?php echo $this->config['action']['update'] ; ?></a>
        <a href="<?php echo $this->url('brand', array('action'=>'delete', 'id' => $brand->getId())); ?>"><?php echo $this->config['action']['delete'] ; ?></a>
    </td>
</tr>
<?php endforeach; ?>
</table>
<?php echo $this->modalHelper(); ?>
