<?php
$title = $this->config['component']['brand'][0];
$action = $this->config['action']['create']['text'];
echo $this->layoutHelper()->header(array(
    'module' => array('url' => $this->url('admin/brand'),'value' => $title),
    ));
    ?>
    <p>
        <a href="<?php echo $this->url('admin/brand', array('action'=>'add'));?>"><label class="<?php echo $this->config['action']['create']['class']; ?>"><i class="<?php echo $this->config['action']['create']['icon']; ?>"></i><?php echo $action ?></label></a>
    </p>

    <table class="table table-striped table-bordered" id='dataTable'>
        <thead>
            <tr>
                <th><?php echo $this->config['component']['name'][1] ;?></th>
                <th><?php echo $this->config['component']['description'][1] ;?></th>
                <th><?php echo $this->config['component']['image'][1] ;?></th>
                <th><?php echo $this->config['component']['background_image'][1] ;?></th>
                <th>&nbsp;</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($brands as $brand) : ?>
                <tr>
                    <td><?php echo $this->escapeHtml($brand->getName());?></td>
                    <td><?php echo $this->escapeHtml($brand->getDescription());?></td>
                    <td class='column-button'>
                        <?php if($brand->getImage()): ?>
                            <a href="javascript:void(0)" class="btn btn-primary btn-xs" onclick="showModalImage('/images/brand/<?php echo $brand->getImage() ?>','<?php echo $this->config['component']['image'][1] ; ?>')">
                                <i class="<?php echo $this->config['action']['image']['icon'] ; ?>"></i>
                            </a>
                        <?php endif; ?>
                    </td>
                    <td class='column-button'>
                        <?php if($brand->getBackgroundImage()): ?>
                            <a href="javascript:void(0)" class="btn btn-primary btn-xs" onclick="showModalImage('/images/brand/<?php echo $brand->getBackgroundImage() ?>','<?php echo $this->config['component']['background_image'][1] ; ?>')">
                                <i class="<?php echo $this->config['action']['image']['icon'] ; ?>"></i>
                            </a>
                        <?php endif; ?>
                    </td>
                    <td class='column-button'>
                        <a href="<?php echo $this->url('admin/brand', array('action'=>'edit', 'id' => $brand->getId())); ?>"><label class="<?php echo $this->config['action']['update']['class']; ?>">
                                <i class="<?php echo $this->config['action']['update']['icon'] ; ?>"></i>
                            </label></a>
                        <a href="<?php echo $this->url('admin/brand', array('action'=>'delete', 'id' => $brand->getId())); ?>"><label class="<?php echo $this->config['action']['delete']['class']; ?>">
                                <i class="<?php echo $this->config['action']['delete']['icon'] ; ?>"></i>
                            </label></a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <?php echo $this->modalHelper()->image(); ?>
    <?php echo $this->paginationControl($brands, 'Sliding', 'pagination',array("route" => "admin/brand")); ?>

