<?php
$title = $this->config['component']['specification'][0];
$action = $this->config['action']['create']['text'];
echo $this->layoutHelper()->header(array(
	'module' => array('url' => $this->url('admin/specification'),'value' => $title),
	'action' => array('url' => '','value' => $action)
	));
	?>
	<?php $form = $this->form; ?>
	<?php $form->setAttribute('action', $this->url('admin/specification', array('action' => 'add'))); ?>
	<?php $form->prepare(); ?>
	<?php echo $this->form()->openTag($form); ?>
	<?php echo $this->formHidden($form->get('id')); ?>
	<?php echo $this->formHidden($form->get('csrf'));?>
	<div class="form-group">
		<?php echo $this->formLabel($form->get('name')->setLabel($this->config['component']['name'][1])); ?>
		<div class="col-sm-4">
			<?php echo $this->formInput($form->get('name')); ?>
			<?php echo $this->formElementErrors($form->get('name'), array("class" => "error")); ?>
		</div>
	</div>
	<div class="form-group">
		<?php echo $this->formLabel($form->get('specification_master')->setLabel($this->config['component']['specification_master'][1])); ?>
		<div class="col-sm-4">
			<?php echo $this->formSelect($form->get('specification_master')); ?>
			<?php echo $this->formElementErrors($form->get('specification_master'), array("class" => "error")); ?>
		</div>
	</div>
	<div class="form-group">
		<?php echo $this->formLabel($form->get('image')); ?>
		<div class="col-sm-4">
			<?php echo $this->formInput($form->get('image')); ?>
			<?php echo $this->formElementErrors($form->get('image'), array("class" => "error")); ?>
			<p class="help-block">
				Extensiones Permitidas: <?php echo implode($this->config['file_characteristics']['image']['extension'],',') ;?><br>
				Tama&ntilde;o: 
				<?php foreach($this->config['file_characteristics']['image']['size'] as $range => $size): ?>
					<?php echo $range." ".$size ; ?>
				<?php endforeach; ?>
			</p>
		</div>
	</div>
	<div class="form-group">
		<?php echo $this->formLabel($form->get('meaning')->setLabel($this->config['component']['meaning'][1])); ?>
		<div class="col-sm-6">
			<?php echo $this->formTextarea($form->get('meaning')); ?>
			<?php echo $this->formElementErrors($form->get('meaning'), array("class" => "error")); ?>
		</div>
	</div>
	<div class="form-group">
		<?php echo $this->formLabel($form->get('general_information')->setLabel($this->config['component']['general_information'][1])); ?>
		<div class="col-sm-6">
			<?php echo $this->formTextarea($form->get('general_information')); ?>
			<?php echo $this->formElementErrors($form->get('general_information'), array("class" => "error")); ?>
		</div>
	</div>
	<div class="well well-sm">
		<?php echo $this->formSubmit($form->get('submit')->setValue($this->config['action']['create']['text'])); ?>
		&nbsp;
		<a href="<?php echo $this->url('admin/specification'); ?>"><label class="<?php echo $this->config['action']['return']['class']; ?>">
<i class="<?php echo $this->config['action']['return']['icon'] ; ?>"></i>
<?php echo $this->config['action']['return']['text']; ?>
</label> </a>
	</div>
	<?php echo $this->form()->closeTag(); ?>