<?php
$title = $this->config['component']['specification'][0];
$this->headTitle($title);
?>
<h2 class="page-header"><?php echo $title ; ?></h2>
<p>
	Esta seguro que quiere borrar '<?php echo $this->escapeHtml($specification->getName()); ?>'?
</p>
<?php
$url = $this->url('admin/specification', array(
	'action' => 'delete',
	'id'=> $this->id,
	));
	?>
	<form action="<?php echo $url; ?>" method="post">
		<div>
			<input type="hidden" name="id" value="<?php echo (int) $specification->getId(); ?>" />
			<?php echo $this->config['action']['delete_yes']; ?>
			<?php echo $this->config['action']['delete_no']; ?>
		</div>
	</form>
