<?php
$title = $this->config['component']['specification'][0];
$this->headTitle($title);
?>
<h2><?php echo $this->escapeHtml($title); ?></h2>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'specification',
    array(
        'action' => 'edit',
        'id'     => $this->id,
    )
));
$form->prepare();?>
<?php echo $this->form()->openTag($form); ?>
<?php echo $this->formHidden($form->get('id')); ?>
<?php echo $this->formHidden($form->get('csrf'));?>
<?php echo $this->formLabel($form->get('name')->setLabel($this->config['component']['name'][1])); ?>
<?php echo $this->formInput($form->get('name')); ?>
<?php echo $this->formElementErrors($form->get('name'), array("class" => "error")); ?>
<?php echo $this->formLabel($form->get('specification_master')->setLabel($this->config['component']['specification_master'][1])); ?>
<?php echo $this->formSelect($form->get('specification_master')); ?>
<?php echo $this->formElementErrors($form->get('specification_master'), array("class" => "error")); ?>

<div class="clearfix"></div>
<?php echo $this->formLabel($form->get('image')); ?>
<?php echo $this->formInput($form->get('image')); ?>
<?php echo $this->formElementErrors($form->get('image'), array("class" => "error")); ?>
<p class="help-block">
Extensiones Permitidas: <?php echo implode($this->config['file_characteristics']['image']['extension'],',') ;?><br>
Tama&ntilde;o: 
<?php foreach($this->config['file_characteristics']['image']['size'] as $range => $size): ?>
	<?php echo $range." ".$size ; ?>
<?php endforeach; ?>
</p>

<?php echo $this->formLabel($form->get('meaning')->setLabel($this->config['component']['meaning'][1])); ?>
<?php echo $this->formTextarea($form->get('meaning')); ?>
<?php echo $this->formElementErrors($form->get('meaning'), array("class" => "error")); ?>
<?php echo $this->formLabel($form->get('general_information')->setLabel($this->config['component']['general_information'][1])); ?>
<?php echo $this->formTextarea($form->get('general_information')); ?>
<?php echo $this->formElementErrors($form->get('general_information'), array("class" => "error")); ?>
<br>
<br>
<?php echo $this->formSubmit($form->get('submit')->setValue($this->config['action']['edit'])); ?>
&nbsp;<a href="/specification"><?php echo $this->config['action']['return'] ; ?></a>
<?php echo $this->form()->closeTag(); ?>