<?php
$title = $this->config['component']['specification'][0];
$this->headTitle($title);
?>
<h2 class="page-header"><?php echo $title ; ?></h2>
<p>
    <a href="<?php echo $this->url('admin/specification', array('action'=>'add'));?>"><?php echo $this->config['action']['add'] ; ?></a>
</p>

<table class="table table-striped table-bordered">
<tr>
    <th><?php echo $this->config['component']['name'][1] ;?></th>
	<th><?php echo $this->config['component']['specification_master'][1] ;?></th>
	<th><?php echo $this->config['component']['image'][1] ;?></th>
	<th><?php echo $this->config['component']['meaning'][1] ;?></th>	
    <th><?php echo $this->config['component']['general_information'][1] ;?></th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($specifications as $specification) : ?>
<tr>
    <td><?php echo $this->escapeHtml($specification->getName());?></td>
    <td><?php echo $this->escapeHtml($specification->getSpecificationMasterName());?></td>
    <td>
        <?php if($specification->getImage()): ?>
            <a href="javascript:void(0)" class="btn btn-primary btn-xs" onclick="showModal('/images/specification/<?php echo $specification->getImage() ?>','<?php echo $this->config['component']['image'][1] ; ?>')"><span class="glyphicon glyphicon-search"></span></a>
        <?php endif; ?>
    </td>
    <td><?php echo $this->escapeHtml($specification->getMeaning());?></td>
    <td><?php echo $this->escapeHtml($specification->getGeneralInformation());?></td>
    <td class='column-button'>
        <a href="<?php echo $this->url('admin/specification',
            array('action'=>'edit', 'id' => $specification->getId())); ?>"><?php echo $this->config['action']['update'] ; ?></a>
        <a href="<?php echo $this->url('admin/specification',
            array('action'=>'delete', 'id' => $specification->getId())); ?>"><?php echo $this->config['action']['delete'] ; ?></a>
    </td>
</tr>
<?php endforeach; ?>
</table>
<?php echo $this->modalHelper(); ?>