<?php
$title = $this->config['component']['payment_method'][0];
$action = $this->config['action']['new'];
echo $this->layoutHelper()->header(array(
	'module' => array('url' => $this->url('admin/payment_method'),'value' => $title),
	'action' => array('url' => '','value' => $action)
	));
	?>
	<?php $form = $this->form; ?>
	<?php $form->setAttribute('action', $this->url('admin/payment_method', array('action' => 'add'))); ?>
	<?php $form->prepare(); ?>
	<?php echo $this->form()->openTag($form); ?>
	<?php echo $this->formHidden($form->get('id')); ?>
	<?php echo $this->formHidden($form->get('csrf'));?>
	<div class="form-group">
		<?php echo $this->formLabel($form->get('name')->setLabel($this->config['component']['name'][1])); ?>
		<div class="col-sm-4">
			<?php echo $this->formInput($form->get('name')); ?>
			<?php echo $this->formElementErrors($form->get('name'), array("class" => "error")); ?>
		</div>
	</div>
	<div class="form-group">
		<?php echo $this->formLabel($form->get('bank_info')->setLabel($this->config['component']['bank_info'][1])); ?>
		<div class="col-sm-4">
			<?php echo $this->formCheckbox($form->get('bank_info')); ?> 
		</div>
	</div>
	<div class="form-group">
		<?php echo $this->formLabel($form->get('description')->setLabel($this->config['component']['description'][1])); ?>
		<div class="col-sm-6">
			<?php echo $this->formTextarea($form->get('description')); ?>
		</div>
	</div>
	<div class="well">
		<?php echo $this->formSubmit($form->get('submit')->setValue($this->config['action']['create'])); ?>
		&nbsp;<a href="<?php echo $this->url('admin/payment_method');?>"><?php echo $this->config['action']['return'] ;?></a>
	</div>
	<?php echo $this->form()->closeTag(); ?>