<?php
$title = $this->config['component']['payment_method'][0];
$action = $this->config['action']['new'];
echo $this->layoutHelper()->header(array(
    'module' => array('url' => $this->url('admin/payment_method'),'value' => $title),
    ));
    ?>
    <p>
        <a href="<?php echo $this->url('admin/payment_method', array('action'=>'add'));?>"><?php echo $this->config['action']['add'] ; ?></a>
    </p>

    <table class="table table-striped table-bordered" id='dataTable'>
        <thead>
            <tr>
                <th><?php echo $this->config['component']['name'][1] ;?></th>
                <th><?php echo $this->config['component']['bank_info'][1] ;?></th>
                <th><?php echo $this->config['component']['description'][1] ;?></th>
                <th>&nbsp;</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($paymentsMethods as $paymentMethod) : ?>
                <tr>
                    <td><?php echo $this->escapeHtml($paymentMethod->getName());?></td>
                    <td><?php 
                        if ($paymentMethod->getBankInfo()):echo "Si" ; else: echo "No" ; endif; ?></td>
                        <td><?php echo $this->escapeHtml($paymentMethod->getDescription());?></td>
                        <td class='column-button'>
                            <a href="<?php echo $this->url('admin/payment_method',
                                array('action'=>'edit', 'id' => $paymentMethod->getId())); ?>"><?php echo $this->config['action']['update'] ; ?></a>
<a href="<?php echo $this->url('admin/payment_method',
    array('action'=>'delete', 'id' => $paymentMethod->getId())); ?>"><?php echo $this->config['action']['delete'] ; ?></a>
</td>
</tr>
<?php endforeach; ?>
</tbody>
</table>
<?php echo $this->paginationControl($paymentsMethods, 'Sliding', 'pagination',array("route" => "admin/payment_method")); ?>
