<?php
$title = $this->config['component']['rol'][0];
$action = $this->config['action']['create']['text'];
echo $this->layoutHelper()->header(array(
	'module' => array('url' => $this->url('security/rol'),'value' => $title),
	'action' => array('url' => '','value' => $action)
	));
	?>
	<?php $form = $this->form; ?>
	<?php $form->setAttribute('action', $this->url('security/rol', array('action' => 'add'))); ?>
	<?php $form->prepare(); ?>
	<?php echo $this->form()->openTag($form); ?>
	<?php echo $this->formHidden($form->get('id')); ?>
	<?php echo $this->formHidden($form->get('csrf'));?>
	<div class="form-group">
		<?php echo $this->formLabel($form->get('name')->setLabel($this->config['component']['name'][1])); ?>
		<div class="col-sm-3">
			<?php echo $this->formInput($form->get('name')); ?>
			<?php echo $this->formElementErrors($form->get('name'), array("class" => "error")); ?>
		</div>
	</div>
	<div class='form-group'>
		<div class="col-sm-4">
			<?php foreach($resources as $module => $resource): ?>
				<h4><?php echo $this->config['component'][$module][0]; ?></h4>
				<?php foreach($resource as $resourceValue): ?>
					<div class='tabulate'><input type='checkbox' value='<?php echo $this->config['component'][$resourceValue][0]; ?>' name='resources[]'>&nbsp;<?php echo $this->config['component'][$resourceValue][0]; ?></div>
				<?php endforeach; ?>
			<?php endforeach; ?>
			<?php echo $this->formElementErrors($form->get('permissions'), array("class" => "error")); ?>
		</div>
	</div>
	<div class="form-group">
		<?php echo $this->formLabel($form->get('description')->setLabel($this->config['component']['description'][1])); ?>
		<div class="col-sm-5">
			<?php echo $this->formTextarea($form->get('description')); ?>
			<?php echo $this->formElementErrors($form->get('description'), array("class" => "error")); ?>
		</div>
	</div>

	<div class="well well-sm">
		<?php echo $this->formSubmit($form->get('submit')->setValue($this->config['action']['create']['text'])); ?>
		<a href="<?php echo $this->url('security/rol');?>">
			<label class="<?php echo $this->config['action']['return']['class']; ?>">
				<i class="<?php echo $this->config['action']['return']['icon'] ; ?>"></i>
				<?php echo $this->config['action']['return']['text']; ?>
			</label>
		</a>
	</div>
	<?php echo $this->form()->closeTag(); ?>
