<?php
$title = $this->config['component']['rol'][0];
$action = $this->config['action']['remove'];
echo $this->layoutHelper()->header(array(
	'module' => array('url' => $this->url('security/rol'),'value' => $title),
	'action' => array('url' => '','value' => $action)
	));
	?>
<div class="alert alert-danger">
	<p>Esta seguro que quiere borrar '<?php echo $this->escapeHtml($rol->getName()); ?>'?</p>
</div>
<?php
$url = $this->url('security/rol', array(
	'action' => 'delete',
	'id'=> $this->id,
	));
	?>
	<form action="<?php echo $url; ?>" method="post">
		<div>
			<input type="hidden" name="id" value="<?php echo (int) $rol->getId(); ?>" />
			<?php echo $this->config['action']['delete_yes']; ?>
			<?php echo $this->config['action']['delete_no']; ?>
		</div>
	</form>

