<?php
$title = $this->config['component']['rol'][0];
$action = $this->config['action']['update']['text'];
echo $this->layoutHelper()->header(array(
	'module' => array('url' => $this->url('security/rol'),'value' => $title),
	'action' => array('url' => '','value' => $action)
	));	

$form = $this->form;
$form->setAttribute('action', $this->url(
	'security/rol',
	array(
		'action' => 'security/edit',
		'id'     => $this->id,
		)
	));
	$form->prepare();?>
	<?php echo $this->form()->openTag($form); ?>
	<?php echo $this->formHidden($form->get('id')); ?>
	<?php echo $this->formHidden($form->get('csrf'));?>
	<div class="form-group">
		<?php echo $this->formLabel($form->get('name')->setLabel($this->config['component']['name'][1])); ?>
		<div class="col-sm-2">
			<?php echo $this->formInput($form->get('name')); ?>
			<?php echo $this->formElementErrors($form->get('name'), array("class" => "error")); ?>
		</div>
	</div>
	<div class='form-group'>
		<div class="col-sm-4">
			<?php foreach($resources as $module => $resource): ?>
				<h4><?php echo $this->config['component'][$module][0]; ?></h4>
				<?php foreach($resource as $resourceValue): ?>
					<?php dump($modulesRoles); ?>
					<?php dumpx($resourceValue); ?>
					<div class='tabulate'><input type='checkbox' value='<?php echo $resourceValue; ?>' name='resources[]'>&nbsp;<?php echo $this->config['component'][$resourceValue][0]; ?>
					</div>
				<?php endforeach; ?>
			<?php endforeach; ?>
			<?php echo $this->formElementErrors($form->get('resources'), array("class" => "error")); ?>
		</div>
	</div>
	<div class="form-group">
		<?php echo $this->formLabel($form->get('description')->setLabel($this->config['component']['description'][1])); ?>
		<div class="col-sm-4">
			<?php echo $this->formTextarea($form->get('description')); ?>
			<?php echo $this->formElementErrors($form->get('description'), array("class" => "error")); ?>
		</div>
	</div>
	<div class="well well-sm">
		<?php echo $this->formSubmit($form->get('submit')->setValue($this->config['action']['update']['text'])); ?>
		&nbsp;
		<a href="<?php echo $this->url('security/rol'); ?>">
			<label class="<?php echo $this->config['action']['return']['class']; ?>">
				<i class="<?php echo $this->config['action']['return']['icon'] ; ?>"></i>
				<?php echo $this->config['action']['return']['text']; ?>
			</label>
		</a>
	</div>
	<?php echo $this->form()->closeTag(); ?>