<?php
$title = $this->config['component']['user'][0];
$this->headTitle($title);
?>


<div class="panel panel-primary">
<div class="panel-heading"><?php echo $title ; ?></div>
	<div class="panel-body">
		<?php $form = $this->form; ?>
		<?php $form->setAttribute('action', $this->url('security/user', array('action' => 'add'))); ?>
		<?php $form->prepare(); ?>
		<?php echo $this->form()->openTag($form); ?>
		<div class="clearfix"></div>
		<?php echo $this->formHidden($form->get('csrf'));?>
		<div class="form-group">
			<div class="col-lg-4">
				<?php echo $this->formLabel($form->get('first_name')->setLabel($this->config['component']['first_name'][0])); ?>
				<?php echo $this->formText($form->get('first_name')); ?>
				<?php echo $this->formElementErrors($form->get('first_name'), array("class" => "error")); ?>
			</div>
		</div>
		<div class="form-group">
			<div class="col-lg-4">
				<?php echo $this->formLabel($form->get('last_name')->setLabel($this->config['component']['last_name'][0])); ?>
				<?php echo $this->formText($form->get('last_name')); ?>
				<?php echo $this->formElementErrors($form->get('last_name'), array("class" => "error")); ?>
			</div>
		</div>
		<div class="form-group">
			<div class="col-lg-3">
				<?php echo $this->formLabel($form->get('username')->setLabel($this->config['component']['username'][1])); ?>
				<?php echo $this->formText($form->get('username')); ?>
				<?php echo $this->formElementErrors($form->get('username'), array("class" => "error")); ?>
			</div>
		</div>
		<div class="form-group">
			<div class="col-lg-3">
				<?php echo $this->formLabel($form->get('email')->setLabel($this->config['component']['email'][1])); ?>
				<?php echo $this->formText($form->get('email')); ?>
				<?php echo $this->formElementErrors($form->get('email'), array("class" => "error")); ?>
			</div>
		</div>
		<div class="form-group">
			<div class="col-lg-3">
				<?php echo $this->formLabel($form->get('roles')->setLabel($this->config['component']['rol'][1])); ?>
				<?php echo $this->formSelect($form->get('roles')); ?>
				<?php echo $this->formElementErrors($form->get('roles'), array("class" => "error")); ?>
			</div>
		</div>
		<div class="form-group">
			<div class="col-lg-4">
				<?php echo $this->formLabel($form->get('password')->setLabel($this->config['component']['password'][1])); ?>
				<div class="input-group">
					<?php echo $this->formPassword($form->get('password')); ?>
					<span class="input-group-addon">
						<input type="checkbox"><span class="glyphicon glyphicon-eye-open"></span>
					</span>
				</div>
				<?php echo $this->formElementErrors($form->get('password'), array("class" => "error")); ?>
			</div>
		</div>
		<div class="form-group">
			<div class="col-lg-4">
				<?php echo $this->formLabel($form->get('password_repeat')->setLabel($this->config['component']['password'][1])); ?>
				<?php echo $this->formPassword($form->get('password_repeat')); ?>
				<?php echo $this->formElementErrors($form->get('password_repeat'), array("class" => "error")); ?>
			</div>
		</div>
		<div class="form-group">
			<div class="col-lg-2">
				<?php echo $this->formLabel($form->get('status')->setLabel($this->config['component']['status'][1])); ?>
				<?php echo $this->formSelect($form->get('status')); ?>
				<?php echo $this->formElementErrors($form->get('status'), array("class" => "error")); ?>
			</div>
		</div>
		<div class="row">
			<div class="span4">
				<div class="form-group">
					<div class="col-lg-8">
						<?php echo $this->formSubmit($form->get('submit')->setValue($this->config['action']['create'])); ?>
						&nbsp;<a href="<?php echo $this->url("security/user"); ?>"><?php echo $this->config['action']['return'] ;?></a>
						<?php echo $this->form()->closeTag(); ?>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
