<?php
$title = $this->config['component']['user'][0];
$this->headTitle($title);
?>
<h1 class="page-header"><?php echo $title ; ?></h1>
<?php $form = $this->form; ?>
<?php $form->setAttribute('action', $this->url('security/user', array('action' => 'edit','id'     => $this->id))); ?>
<?php $form->prepare(); ?>
<?php echo $this->form()->openTag($form); ?>
<div class="clearfix"></div>
<div class="form-group">
	<div class="col-lg-4">
		<?php echo $this->formHidden($form->get('csrf'));?>
		<?php echo $this->formLabel($form->get('first_name')->setLabel($this->config['component']['first_name'][0])); ?>
		<?php echo $this->formText($form->get('first_name')); ?>
		<?php echo $this->formElementErrors($form->get('first_name'), array("class" => "error")); ?>
	</div>
</div>
<div class="form-group">
	<div class="col-lg-4">
		<?php echo $this->formLabel($form->get('last_name')->setLabel($this->config['component']['last_name'][0])); ?>
		<?php echo $this->formText($form->get('last_name')); ?>
		<?php echo $this->formElementErrors($form->get('last_name'), array("class" => "error")); ?>
	</div>
</div>
<div class="form-group">
	<div class="col-lg-3">
		<?php echo $this->formLabel($form->get('username')->setLabel($this->config['component']['username'][1])); ?>
		<?php echo $this->formText($form->get('username')); ?>
		<?php echo $this->formElementErrors($form->get('username'), array("class" => "error")); ?>
	</div>
</div>
<div class="form-group">
	<div class="col-lg-4">
		<?php echo $this->formLabel($form->get('email')->setLabel($this->config['component']['email'][1])); ?>
		<?php echo $this->formText($form->get('email')); ?>
		<?php echo $this->formElementErrors($form->get('email'), array("class" => "error")); ?>
	</div>
</div>
<div class="form-group">
	<div class="col-lg-4">
		<?php echo $this->formLabel($form->get('picture')->setLabel($this->config['component']['picture'][1])); ?>
		<?php echo $this->formInput($form->get('picture')); ?>
		<?php echo $this->formElementErrors($form->get('picture'), array("class" => "error")); ?>
		<p class="help-block">
			Extensiones Permitidas: <?php echo implode($this->config['file_characteristics']['image']['extension'],',') ;?><br>
			Tama&ntilde;o: 
			<?php foreach($this->config['file_characteristics']['image']['size'] as $range => $size): ?>
				<?php echo $range." ".$size ; ?>
			<?php endforeach; ?>
		</p>
	</div>
</div>
<div class="form-group">
	<div class="col-lg-4">
		<?php echo $this->formLabel($form->get('signature')->setLabel($this->config['component']['signature'][1])); ?>
		<?php echo $this->formInput($form->get('signature')); ?>
		<?php echo $this->formElementErrors($form->get('signature'), array("class" => "error")); ?>
		<p class="help-block">
			Extensiones Permitidas: <?php echo implode($this->config['file_characteristics']['image']['extension'],',') ;?><br>
			Tama&ntilde;o: 
			<?php foreach($this->config['file_characteristics']['image']['size'] as $range => $size): ?>
				<?php echo $range." ".$size ; ?>
			<?php endforeach; ?>
		</p>
	</div>
</div>
<div class="form-group">
	<div class="col-lg-2">
		<?php echo $this->formLabel($form->get('rol')->setLabel($this->config['component']['rol'][1])); ?>
		<?php echo $this->formSelect($form->get('rol')); ?>
		<?php echo $this->formElementErrors($form->get('rol'), array("class" => "error")); ?>
	</div>
</div>
<div class="form-group">
	<div class="col-lg-2">
		<?php echo $this->formLabel($form->get('status')->setLabel($this->config['component']['status'][1])); ?>
		<?php echo $this->formSelect($form->get('status')); ?>
		<?php echo $this->formElementErrors($form->get('status'), array("class" => "error")); ?>
	</div>
</div>
<div class="row">
	<div class="span4">
		<div class="form-group">
			<div class="col-lg-8">
				<?php echo $this->formSubmit($form->get('submit')->setValue($this->config['action']['create'])); ?>
				&nbsp;<a href="<?php echo $this->url("security/user"); ?>"><?php echo $this->config['action']['return'] ;?></a>
				<?php echo $this->form()->closeTag(); ?>
			</div>
		</div>
	</div>
</div>