<?php
$title = $this->config['component']['user'][0];
$action = $this->config['action']['create']['text'];
echo $this->layoutHelper()->header(array(
    'module' => array('url' => $this->url('security/user'),'value' => $title),
    ));
    ?>
    <p>
        <a href="<?php echo $this->url('security/user', array('action'=>'add'));?>">
            <label class="<?php echo $this->config['action']['create']['class']; ?>"><i class="<?php echo $this->config['action']['create']['icon']; ?>"></i><?php echo $action; ?></label>
        </a>
    </p>
    <table class="table table-striped table-bordered table-hover">
        <tr>
            <th><?php echo $this->config['component']['first_name'][1] ;?></th>
            <th><?php echo $this->config['component']['last_name'][1] ;?></th>
            <th><?php echo $this->config['component']['username'][1] ;?></th>
            <th><?php echo $this->config['component']['email'][1] ;?></th>
            <th><?php echo $this->config['component']['rol'][1] ;?></th>
            <th><?php echo $this->config['component']['status'][1] ;?></th>
            <th>&nbsp;</th>
        </tr>
        <?php foreach ($users as $user) : ?>
            <tr>
                <td><?php echo $this->escapeHtml($user->getFirstName());?></td>
                <td><?php echo $this->escapeHtml($user->getLastName());?></td>
                <td><?php echo $this->escapeHtml($user->getUsername());?></td>
                <td><?php echo $this->escapeHtml($user->getEmail());?></td>
                <td><?php echo $this->escapeHtml($user->getRolName());?></td>
                <td><?php echo $this->escapeHtml($user->getStatus());?></td>
                <td class='column-button'>
                    <a href="<?php echo $this->url('security/user', array('action'=>'edit', 'id' => $user->getId())); ?>">
                        <label class="<?php echo $this->config['action']['update']['class']; ?>">
                         <i class="<?php echo $this->config['action']['update']['icon'] ; ?>"></i>
                     </label>
                 </a>
                 <a href="<?php echo $this->url('security/user', array('action'=>'delete', 'id' => $user->getId())); ?>">
                    <label class="<?php echo $this->config['action']['delete']['class']; ?>">
                       <i class="<?php echo $this->config['action']['delete']['icon'] ; ?>"></i>
                   </label>
               </a>
           </td>
       </tr>
   <?php endforeach; ?>
</table>