<?php
$title = $this->config['component']['user_type'][0];
$action = $this->config['action']['create']['text'];
echo $this->layoutHelper()->header(array(
    'module' => array('url' => $this->url('admin/user_type'),'value' => $title),
    ));
    ?>
    <p>
        <a href="<?php echo $this->url('admin/user_type', array('action'=>'add'));?>"><label class="<?php echo $this->config['action']['create']['class']; ?>"><i class="<?php echo $this->config['action']['create']['icon']; ?>"></i><?php echo $action ?></label></a>
    </p>

    <table class="table table-striped table-bordered table-hover" id='dataTable'>
        <thead>
            <tr>
                <th><?php echo $this->config['component']['name'][1] ;?></th>
                <th><?php echo $this->config['component']['description'][1] ;?></th>
                <th>&nbsp;</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($userTypes as $userType) : ?>
                <tr>
                    <td><?php echo $this->escapeHtml($userType->getName());?></td>
                    <td><?php echo $this->escapeHtml($userType->getDescription());?></td>
                    <td class='column-button'>
                        <a href="<?php echo $this->url('admin/user_type',
                            array('action'=>'edit', 'id' => $userType->getId())); ?>"><label class="<?php echo $this->config['action']['update']['class']; ?>">
                            <i class="<?php echo $this->config['action']['update']['icon'] ; ?>"></i>
                        </label></a>
                        <a href="<?php echo $this->url('admin/user_type',
                            array('action'=>'delete', 'id' => $userType->getId())); ?>"><label class="<?php echo $this->config['action']['delete']['class']; ?>">
                            <i class="<?php echo $this->config['action']['delete']['icon'] ; ?>"></i>
                        </label></a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <?php echo $this->paginationControl($userTypes, 'Sliding', 'pagination',array("route" => "admin/user_type")); ?>
