<?php
$this->headScript()->prependFile('/js/details-receive-inventory.js', 'text/javascript');

$title1 = $this->config['component']['receive_inventory'][0];
$title2 = $this->config['component']['detail_receive_inventory'][0];
$action = $this->config['action']['detail'];
echo $this->layoutHelper()->header(array(
	'module' => array('url' => $this->url('process/receive_inventory/add'),'value' => $title1),
	'action' => array('url' => $this->url('process/receive_inventory/add/details'),'value' => $title2)
	));
	?>
	<div class="form-group">
		<div class="col-sm-12">
			<div class="panel panel-default">
				<div class="panel-heading"></div>
				<table class="table table-bordered">
					<thead>
						<tr>
							<th><?php echo $config['component']['number'][1]; ?></th>
							<th><?php echo $config['component']['register_date'][1]; ?></th>
							<th><?php echo $config['component']['customer'][1]; ?></th>
							<th><?php echo $config['component']['payment_method'][1]; ?></th>
							<th><?php echo $config['component']['shipment'][1]; ?></th>
							<th><?php echo $config['component']['guide_number'][1]; ?></th>
							<th><?php echo $config['component']['invoice'][1]; ?></th>
							<th><?php echo $config['component']['invoice_file'][1]; ?></th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td><b><?php echo $receiveInventory->getId(); ?></b></td>
							<td><?php echo $receiveInventory->getRegisterDate(); ?></td>
							<td><?php echo $receiveInventory->getCustomerFirstName()." ".$receiveInventory->getCustomerLastName(); ?></td>
							<td><?php echo $receiveInventory->getPaymentMethodName(); ?></td>
							<td><?php echo $receiveInventory->getShipmentFirstName()." ".$receiveInventory->getShipmentLastName(); ?></td>
							<td><?php echo $receiveInventory->getGuideNumber(); ?></td>
							<td><?php echo $receiveInventory->getInvoice(); ?></td>
							<td>
								<?php if($receiveInventory->getInvoiceFile()): ?>
									<a href="/files/receive_inventory/<?php echo $receiveInventory->getInvoiceFile()?>" class="btn btn-primary btn-xs" target='_blank'>
										<span class="glyphicon glyphicon-floppy-disk"></span></a>
									<?php endif; ?>
								</td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		</div>
		<div class='clearfix'></div>
		<?php $form = $this->form; ?>
		<?php $form->setAttribute('action', $this->url('process/receive_inventory/add/details', array('action' => 'add'))); ?>
		<?php $form->prepare(); ?>
		<?php echo $this->form()->openTag($form); ?>
		<?php echo $this->formHidden($form->get('csrf')); ?>
		<div class="form-group">
			<?php echo $this->formLabel($form->get('cost')->setLabel($this->config['component']['cost'][1])); ?>
			<div class="col-sm-3">
				<div class="input-group">
					<span class="input-group-addon">$</span>
					<?php echo $this->formInput($form->get('cost')); ?>
					<span class="input-group-addon">.00</span>
				</div>

				<?php echo $this->formElementErrors($form->get('cost'), array("class" => "error")); ?>
			</div>
		</div>
		<div class="form-group">
			<?php echo $this->formLabel($form->get('iva')->setLabel($this->config['component']['iva'][1])); ?>
			<div class="col-sm-3">
				<?php echo $this->formSelect($form->get('iva')); ?>
				<?php echo $this->formElementErrors($form->get('iva'), array("class" => "error")); ?>
			</div>
		</div>
		<div class="form-group">
			<?php echo $this->formLabel($form->get('qty')->setLabel($this->config['component']['qty'][1])); ?>
			<div class="col-sm-2">
				<?php echo $this->formInput($form->get('qty')); ?>
				<?php echo $this->formElementErrors($form->get('qty'), array("class" => "error")); ?>
			</div>
		</div>
		<div class="form-group">
			<?php echo $this->formLabel($form->get('product_search')->setLabel($this->config['component']['product'][1])); ?>
			<div class="col-sm-4">
				<?php echo $this->formInput($form->get('product_search')); ?>
				<?php echo $this->formSelect($form->get('product')); ?>
				<?php echo $this->formElementErrors($form->get('product'), array("class" => "error")); ?>
			</div>
		</div>
		<div class="form-group">
			<div class="col-sm-6">
				<?php if(!empty($serialValuesMessageError) && $serialValuesMessageError): ?>
					<div class='alert alert-danger'><button type='button' class='close' data-dismiss='alert'><span aria-hidden='true'>×</span><span class='sr-only'>Close</span></button><p><?php echo $serialValuesMessageError; ?></p></div>
				<?php endif; ?>
			</div>
		</div>
		<div class="form-group">
			<div class="col-sm-12">
				<div id="serial_values_layout">
				</div>
			</div>
		</div>
		<div class="form-group">
			<?php echo $this->formLabel($form->get('manifest_file')->setLabel($this->config['component']['manifest_file'][1])); ?>
			<div class="col-sm-4">
				<?php echo $this->formInput($form->get('manifest_file')); ?>
				<?php echo $this->formElementErrors($form->get('manifest_file'), array("class" => "error")); ?>
			</div>
		</div>
		<?php echo $this->formSubmit($form->get('submit')->setValue($this->config['action']['create'])); ?>
		<?php echo $this->form()->closeTag(); ?>
		<br>
		<?php if(isset($detailsReceiveInventory) && $detailsReceiveInventory->count()>0): ?>
			<div class="panel panel-default">
				<div class="panel-heading"><h5><?php echo $title2; ?></h5></div>
				<table class="table table-bordered">
					<thead>
						<tr>
							<th><?php echo $config['component']['cost'][1]; ?></th>
							<th><?php echo $config['component']['iva'][1]; ?></th>
							<th><?php echo $config['component']['product'][1]; ?></th>
							<th><?php echo $config['component']['qty'][1]; ?></th>
							<th><?php echo $config['component']['serial_name'][1]; ?></th>
							<th><?php echo $config['component']['manifest_file'][1]; ?></th>
						</tr>
					</thead>
					<?php foreach($detailsReceiveInventory as $detailsReceiveInventory): ?>
						<tbody>
							<tr>
								<td>$ <?php echo number_format($detailsReceiveInventory->getCost()); ?></td>
								<td><?php echo $detailsReceiveInventory->getIva(); ?></td>
								<td><?php echo $detailsReceiveInventory->getProduct(); ?></td>
								<td><?php echo $detailsReceiveInventory->getQty(); ?></td>
								<td>
									<a href="javascript:void(0)" class="btn btn-primary se-xs" onclick='showModalList("<?php echo addslashes($detailsReceiveInventory->getSerials()); ?>","<?php echo $this->config['component']['serial_name'][0] ?>");'>
                                    <span class="glyphicon glyphicon-th-list"></span></a>
								</td>
								<td><?php echo $detailsReceiveInventory->getManifestFile(); ?></td>
							</tr>
						</tbody>
					<?php endforeach; ?>
				</table>
			</div>
		<?php endif; ?>
		<div class="well well-sm">
			<a href="<?php echo $this->url('admin/app'); ?>"><?php echo $this->config['action']['finish'] ; ?> </a>
		</div>
		<?php echo $this->modalHelper()->listContent(); ?>
