<?php
$this->headScript()->prependFile('/js/details-receive-inventory.js', 'text/javascript');

$title = $this->config['component']['receive_inventory'][0];
$action = $this->config['action']['detail'];
echo $this->layoutHelper()->header(array(
	'module' => array('url' => $this->url('process/receive_inventory'),'value' => $title),
	'action' => array('url' => '','value' => $action)
	));
	?>
	<div class="form-group">
		<div class="col-sm-10">
			<div class="panel panel-default">
				<div class="panel-heading"><?php echo $config['component']['receive_inventory'][0]; ?></div>
				<table class="table table-bordered">
					<thead>
						<tr>
							<th><?php echo $config['component']['register_date'][1]; ?></th>
							<th><?php echo $config['component']['customer'][1]; ?></th>
							<th><?php echo $config['component']['payment_method'][1]; ?></th>
							<th><?php echo $config['component']['shipment'][1]; ?></th>
							<th><?php echo $config['component']['guide_number'][1]; ?></th>
							<th><?php echo $config['component']['invoice'][1]; ?></th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td><?php echo $receiveInventory->getRegisterDate(); ?></td>
							<td><?php echo $receiveInventory->getCustomerFirstName()." ".$receiveInventory->getCustomerLastName(); ?></td>
							<td><?php echo $receiveInventory->getPaymentMethodName(); ?></td>
							<td><?php echo $receiveInventory->getShipmentFirstName()." ".$receiveInventory->getShipmentLastName(); ?></td>
							<td><?php echo $receiveInventory->getGuideNumber(); ?></td>
							<td><?php echo $receiveInventory->getInvoice(); ?></td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
	</div>
	<div class='clearfix'></div>

	<?php $form = $this->form; ?>
	<?php $form->setAttribute('action', $this->url('process/receive_inventory', array('action' => 'add'))); ?>
	<?php $form->prepare(); ?>
	<?php echo $this->form()->openTag($form); ?>
	<?php echo $this->formHidden($form->get('id')); ?>
	<?php echo $this->formHidden($form->get('csrf')); ?>
	<div class="form-group">
		<?php echo $this->formLabel($form->get('cost')->setLabel($this->config['component']['cost'][1])); ?>
		<div class="col-sm-3">
			<div class="input-group">
				<span class="input-group-addon">$</span>
				<?php echo $this->formInput($form->get('cost')); ?>
				<span class="input-group-addon">.00</span>
			</div>

			<?php echo $this->formElementErrors($form->get('cost'), array("class" => "error")); ?>
		</div>
	</div>
	<div class="form-group">
		<?php echo $this->formLabel($form->get('iva')->setLabel($this->config['component']['iva'][1])); ?>
		<div class="col-sm-3">
			<?php echo $this->formSelect($form->get('iva')); ?>
			<?php echo $this->formElementErrors($form->get('iva'), array("class" => "error")); ?>
		</div>
	</div>
	<div class="form-group">
		<?php echo $this->formLabel($form->get('qty')->setLabel($this->config['component']['qty'][1])); ?>
		<div class="col-sm-1">
			<?php echo $this->formInput($form->get('qty')); ?>
			<?php echo $this->formElementErrors($form->get('qty'), array("class" => "error")); ?>
		</div>
	</div>
	<div class="form-group">
		<?php echo $this->formLabel($form->get('product_search')->setLabel($this->config['component']['product'][1])); ?>
		<div class="col-sm-4">
			<?php echo $this->formInput($form->get('product_search')); ?>
			<?php echo $this->formSelect($form->get('product')); ?>
			<?php echo $this->formElementErrors($form->get('product'), array("class" => "error")); ?>
		</div>
	</div>
	<div class="form-group">
		<div class="col-sm-12">
			<div id="serial_values_layout">
			</div>
		</div>
	</div>
	<div class="form-group">
		<?php echo $this->formLabel($form->get('manifest_file')->setLabel($this->config['component']['manifest_file'][1])); ?>
		<div class="col-sm-4">
			<?php echo $this->formInput($form->get('manifest_file')); ?>
			<?php echo $this->formElementErrors($form->get('manifest_file'), array("class" => "error")); ?>
		</div>
	</div>
	<div class="well well-sm">
		<?php echo $this->formSubmit($form->get('submit')->setValue($this->config['action']['create'])); ?>
	</div>
	<?php echo $this->form()->closeTag(); ?>
	<?php echo $this->modalHelper()->userAdd(); ?>
