<?php
$title = $this->config['component']['details_receive_inventory'][0];
$title1 = $this->config['component']['receive_inventory'][0];
$title2 = $this->config['component']['details_receive_inventory'][0];
$action = $this->config['action']['remove'];

echo $this->layoutHelper()->header(array(
	'module' => array('url' => $this->url('process/receive_inventory/add'),'value' => $title1),
	'action' => array('url' => $this->url('process/receive_inventory/add/details'),'value' => $title2)
	));
	?>

	<?php if(isset($error) && $error): ?>
		<div class="alert alert-danger fade in">
			<h4 class='clear-text'>¡Vaya! Se ha producido un error.</h4>
			<p>No se puede borrar el registro de <?php echo $title; ?> ya que este se encuentra vinculado a otro registro.</p>
			<p>
				<a href="<?php echo $this->url('process/receive_inventory/add/details');?>"><?php echo $this->config['action']['return'] ; ?> </a>
			</p>
		</div>
	<?php else: ?>

		<div class="alert alert-danger">
			<p>Esta seguro que quiere finalizar la entrada?</p>
		</div>
		<?php
		$url = $this->url('process/receive_inventory/finish', array(
			'id'=> $this->id,
			));
			?>
			<form action="<?php echo $url; ?>" method="post">
				<div class="well well-sm">
					<input type="submit" name="del" value="Si" class="btn btn-danger btn-sm"/>
					<input type="submit" name="del" value="No" class="btn btn-default btn-sm"/>
				</div>
			</form>
		<?php endif; ?>
