<?php
$title = $this->config['component']['measure_type'][0];
$this->headTitle($title);
?>
<h2 class="page-header"><?php echo $title ; ?></h2>
<?php $form = $this->form; ?>
<?php $form->setAttribute('action', $this->url('admin/measure_type', array('action' => 'add'))); ?>
<?php $form->prepare(); ?>
<?php echo $this->form()->openTag($form); ?>
<?php echo $this->formHidden($form->get('id')); ?>
<?php echo $this->formHidden($form->get('csrf'));?>
<div class="form-group">
	<div class="col-lg-4">
		<?php echo $this->formLabel($form->get('abbreviation')->setLabel($this->config['component']['abbreviation'][1])); ?>
		<?php echo $this->formInput($form->get('abbreviation')); ?>
		<?php echo $this->formElementErrors($form->get('abbreviation'), array("class" => "error")); ?>
	</div>
</div>
<div class="form-group">
	<div class="col-lg-4">
		<?php echo $this->formLabel($form->get('name')->setLabel($this->config['component']['name'][1])); ?>
		<?php echo $this->formInput($form->get('name')); ?>
		<?php echo $this->formElementErrors($form->get('name'), array("class" => "error")); ?>
	</div>
</div>
<div class="form-group">
	<div class="col-lg-6">
		<?php echo $this->formLabel($form->get('description')->setLabel($this->config['component']['description'][1])); ?>
		<?php echo $this->formTextarea($form->get('description')); ?>
	</div>
</div>
<?php echo $this->formSubmit($form->get('submit')->setValue($this->config['action']['create'])); ?>
&nbsp;<a href="<?php echo $this->url('admin/measure_type'); ?>"><?php echo $this->config['action']['return'] ;?></a>
<?php echo $this->form()->closeTag(); ?>