<?php
$title = $this->config['component']['measure_type'][0];
$this->headTitle($title);
?>
<h2><?php echo $this->escapeHtml($title); ?></h2>
<p>
    <a href="<?php echo $this->url('measure_type', array('action'=>'add'));?>"><?php echo $this->config['action']['add'] ; ?></a>
</p>

<table class="table table-striped table-bordered">
<tr>
	<th><?php echo $this->config['component']['abbreviation'][1]; ?></th>
    <th><?php echo $this->config['component']['name'][1]; ?></th>
    <th><?php echo $this->config['component']['description'][1]; ?></th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($measuresTypes as $measureType) : ?>
<tr>
	<td><?php echo $this->escapeHtml($measureType->getAbbreviation());?></td>
    <td><?php echo $this->escapeHtml($measureType->getName());?></td>
    <td><?php echo $this->escapeHtml($measureType->getDescription());?></td>
    <td class='column-button'>
        <a href="<?php echo $this->url('measure_type',
            array('action'=>'edit', 'id' => $measureType->getId())); ?>"><?php echo $this->config['action']['update'] ; ?></a>
        <a href="<?php echo $this->url('measure_type',
            array('action'=>'delete', 'id' => $measureType->getId())); ?>"><?php echo $this->config['action']['delete'] ; ?></a>
    </td>
</tr>
<?php endforeach; ?>
</table>