<?php
$title = $this->config['component']['classification'][0];
$action = $this->config['action']['create']['text'];
$this->headTitle($title);
?>
<h2 class="page-header"><?php echo $title ; ?></h2>
<p>
    <a href="<?php echo $this->url('admin/classification', array('action'=>'add'));?>"><label class="<?php echo $this->config['action']['create']['class']; ?>"><i class="<?php echo $this->config['action']['create']['icon']; ?>"></i><?php echo $action ?></label></a>
</p>

<table class="table table-striped table-bordered" id='dataTable'>
    <thead>
        <tr>
            <th><?php echo $this->config['component']['name'][1] ;?></th>
            <th><?php echo $this->config['component']['user_type'][1] ;?></th>
            <th><?php echo $this->config['component']['description'][1] ;?></th>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($classifications as $classification) : ?>
            <tr>
                <td><?php echo $this->escapeHtml($classification->getName());?></td>
                <td><?php echo $this->escapeHtml($classification->getUserTypeName());?></td>
                <td><?php echo $this->escapeHtml($classification->getDescription());?></td>
                <td class='column-button'>
                    <a href="<?php echo $this->url('admin/classification',
                        array('action'=>'edit', 'id' => $classification->getId())); ?>"><label class="<?php echo $this->config['action']['update']['class']; ?>">
                        <i class="<?php echo $this->config['action']['update']['icon'] ; ?>"></i>
                    </label></a>
                    <a href="<?php echo $this->url('admin/classification',
                        array('action'=>'delete', 'id' => $classification->getId())); ?>"><label class="<?php echo $this->config['action']['delete']['class']; ?>">
                        <i class="<?php echo $this->config['action']['delete']['icon'] ; ?>"></i>
                    </label></a>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<?php echo $this->modalHelper()->image(); ?>
<?php echo $this->paginationControl($classifications, 'Sliding', 'pagination',array("route" => "admin/classification")); ?>
