<div class="modal fade" id="modalImage" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="modalImageLabel"></h4>
      </div>
      <div class="modal-body" align='center' id="modalBody">
        <img src="" class="img-thumbnail">
      </div>
    </div>
  </div>
</div>