<div class="modal fade" id="modalNote" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title">Notas</h4>
			</div>
			<div class="modal-body" id="modalBody">
				<div class='pull-right'>
					<a href='javascript:void(0)' id='add_note'>
						<label class="<?php echo $this->config['action']['add']['class']; ?>">
							<i class="<?php echo $this->config['action']['add']['icon']; ?>"></i><?php echo $this->config['action']['add']['text']; ?>
						</label>
					</a>
				</div>

				<?php $form = $this->form; ?>
				<div id='layout_add_note'>
					<?php $form->setAttribute('action', $this->url('admin/bank', array('action' => 'add'))); ?>
					<?php $form->prepare(); ?>
					<?php echo $this->form()->openTag($form); ?>
					<?php echo $this->formHidden($form->get('id')); ?>
					<?php echo $this->formHidden($form->get('csrf'));?>
					<div class="form-group">
						<?php echo $this->formLabel($form->get('title')->setLabel($this->config['component']['title'][1])); ?>
						<div class="col-sm-8">
							<?php echo $this->formInput($form->get('title')); ?>
							<?php echo $this->formElementErrors($form->get('title'), array("class" => "error")); ?>
						</div>
					</div>
					<div class="form-group">
						<?php echo $this->formLabel($form->get('content')->setLabel($this->config['component']['content'][1])); ?>
						<div class="col-sm-8">
							<?php echo $this->formTextarea($form->get('content')); ?>
							<?php echo $this->formElementErrors($form->get('content'), array("class" => "error")); ?>
						</div>
					</div>
					<a href='javascript:void(0)' id='save_note'>
						<label class="<?php echo $this->config['action']['create']['class']; ?>"><i class="<?php echo $this->config['action']['create']['icon']; ?>"></i><?php echo $this->config['action']['create']['text']; ?></label>
					</a>
					<?php echo $this->form()->closeTag(); ?>
				</div>
				<div class='clearfix'></div><br>
				<div class="message_note"></div>
				<div class="panel-group" id="accordion">
					<?php foreach($notes as $key => $note): ?>
						<div class="panel panel-yellow" id='panel_note_<?php echo $note->getId(); ?>'>
							<div class="panel-heading">
								<h4 class="panel-title">
									<a data-toggle="collapse" data-parent="#accordion" href="#note<?php echo $note->getId(); ?>" class='clear-text'><?php echo $note->getTitle(); ?></a>
									<div class='pull-right'>
										<button type="button" class="close delete_note" noteValue='<?php echo $note->getId(); ?>'><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
									</div>
								</h4>
							</div>
							<?php $status = $key == 0 ? "in" : "" ?>
							<div id="note<?php echo $note->getId(); ?>" class="panel-collapse collapse <?php echo $status; ?>">
								<div class="panel-body"><?php echo $note->getContent(); ?></div>
							</div>
						</div>
					<?php endforeach; ?>
				</div>
			</div>
		</div>
	</div>
</div>