<?php
$title = $this->config['component']['bank'][0];
$action = $this->config['action']['create']['text'];
echo $this->layoutHelper()->header(array(
    'module' => array('url' => $this->url('admin/bank'),'value' => $title),
    ));
    ?>
    <p>
        <a href="<?php echo $this->url('admin/bank', array('action'=>'add'));?>">
            <label class="<?php echo $this->config['action']['create']['class']; ?>"><i class="<?php echo $this->config['action']['create']['icon']; ?>"></i><?php echo $action; ?></label>
        </a>
    </p>

    <table class="table table-striped table-bordered table-hover table-responsive" id='dataTable'>
        <thead>
            <tr>
                <th><?php echo $this->config['component']['name'][1] ;?></th>
                <th><?php echo $this->config['component']['description'][1] ;?></th>
                <th>&nbsp;</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($banks as $bank) : ?>
                <tr>
                    <td><?php echo $this->escapeHtml($bank->getName());?></td>
                    <td><?php echo $this->escapeHtml($bank->getDescription());?></td>
                    <td class='column-button'>
                        <a href="<?php echo $this->url('admin/bank',
                            array('action'=>'edit', 'id' => $bank->getId())); ?>">

                            <label class="<?php echo $this->config['action']['update']['class']; ?>">
                                <i class="<?php echo $this->config['action']['update']['icon'] ; ?>"></i>
                            </label>
                        </a>
                        <a href="<?php echo $this->url('admin/bank',
                            array('action'=>'delete', 'id' => $bank->getId())); ?>">
                            <label class="<?php echo $this->config['action']['delete']['class']; ?>">
                               <i class="<?php echo $this->config['action']['delete']['icon'] ; ?>"></i>
                           </label>
                       </a>
                   </a>
               </td>
           </tr>
       <?php endforeach; ?>
       <tbody>
       </table>
       <?php echo $this->paginationControl($banks, 'Sliding', 'pagination',array("route" => "admin/bank")); ?>