<?php
$title = $this->config['component']['user_shortcut'][0];
$this->headTitle($title);
?>
<h2 class="page-header"><?php echo $title ; ?></h2>
<p>
    <a href="<?php echo $this->url('settings/user_shortcut', array('action'=>'add'));?>"><?php echo $this->config['action']['add'] ; ?></a>
</p>

<table class="table table-striped table-bordered table-hover">
    <tr>
        <th><?php echo $this->config['component']['name'][1] ;?></th>
        <th><?php echo $this->config['component']['description'][1] ;?></th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($userShortCuts as $userShortCut) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($userShortCut->getModuleName());?></td>
            <td><?php echo $this->escapeHtml($userShortCut->GetUserName());?></td>
            <td class='column-button'>
                <a href="<?php echo $this->url('settings/user_shortcut', array('action'=>'edit', 'id' => $userShortCut->getId())); ?>"><?php echo $this->config['action']['update'] ; ?></a>
                <a href="<?php echo $this->url('settings/user_shortcut', array('action'=>'delete', 'id' => $userShortCut->getId())); ?>"><?php echo $this->config['action']['delete'] ; ?></a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>