<?php
$title = $this->config['component']['measure'][0];
$this->headTitle($title);
?>
<h2><?php echo $this->escapeHtml($title); ?></h2>
<br>
<?php $form = $this->form; ?>
<?php $form->setAttribute('action', $this->url('measure', array('action' => 'add'))); ?>
<?php $form->prepare(); ?>
<?php echo $this->form()->openTag($form); ?>
<?php echo $this->formHidden($form->get('id')); ?>
<?php echo $this->formHidden($form->get('csrf'));?>
<?php echo $this->formLabel($form->get('specification')->setLabel($this->config['component']['specification'][1])); ?>
<?php echo $this->formSelect($form->get('specification')); ?>
<?php echo $this->formElementErrors($form->get('specification'), array("class" => "error")); ?>

<?php echo $this->formLabel($form->get('measure_type')->setLabel($this->config['component']['measure_type'][1])); ?>
<?php echo $this->formSelect($form->get('measure_type')); ?>
<?php echo $this->formElementErrors($form->get('measure_type'), array("class" => "error")); ?>

<?php echo $this->formLabel($form->get('measure_value')->setLabel($this->config['component']['measure_value'][1])); ?>
<?php echo $this->formInput($form->get('measure_value')); ?>
<?php echo $this->formElementErrors($form->get('measure_value'), array("class" => "error")); ?>

<div class="clearfix"></div>
<?php echo $this->formLabel($form->get('image')); ?>
<?php echo $this->formInput($form->get('image')); ?>
<?php echo $this->formElementErrors($form->get('image'), array("class" => "error")); ?>
<p class="help-block">
Extensiones Permitidas: <?php echo implode($this->config['file_characteristics']['image']['extension'],',') ;?><br>
Tama&ntilde;o: 
<?php foreach($this->config['file_characteristics']['image']['size'] as $range => $size): ?>
	<?php echo $range." ".$size ; ?>
<?php endforeach; ?>
</p>

<?php echo $this->formLabel($form->get('meaning')->setLabel($this->config['component']['meaning'][1])); ?>
<?php echo $this->formTextarea($form->get('meaning')); ?>

<?php echo $this->formLabel($form->get('general_information')->setLabel($this->config['component']['general_information'][1])); ?>
<?php echo $this->formTextarea($form->get('general_information')); ?>
<br><br>
<?php echo $this->formSubmit($form->get('submit')->setValue($this->config['action']['create'])); ?>
&nbsp;<a href="/measure-type"><?php echo $this->config['action']['return'] ;?></a>
<?php echo $this->form()->closeTag(); ?>