<?php
$title = $this->config['component']['measure'][0];
$action = $this->config['action']['new'];
echo $this->layoutHelper()->header(array(
  'module' => array('url' => $this->url('admin/measure'),'value' => $title),
  ));
  ?>
  <p>
    <a href="<?php echo $this->url('admin/measure', array('action'=>'add'));?>"><?php echo $this->config['action']['add'] ; ?></a>
  </p>

  <table class="table table-striped table-bordered" id='dataTable'>
    <thead>
      <tr>
       <th><?php echo $this->config['component']['specification'][1]; ?></th>
       <th><?php echo $this->config['component']['measure_type'][1]; ?></th>
       <th><?php echo $this->config['component']['measure_value'][1]; ?></th>
       <th><?php echo $this->config['component']['image'][1]; ?></th>
       <th><?php echo $this->config['component']['meaning'][1]; ?></th>
       <th><?php echo $this->config['component']['general_information'][1]; ?></th>
       <th>&nbsp;</th>
     </tr>
   </thead>
   <tbody>
     <?php foreach ($measures as $measure) : ?>
      <tr>
       <td><?php echo $this->escapeHtml($measure->getSpecificationName());?></td>
       <td><?php echo $this->escapeHtml($measure->getMeasureTypeName());?></td>
       <td><?php echo $this->escapeHtml($measure->getMeasureValue());?></td>
       <td>
        <?php if($measure->getImage()): ?>
          <a href="javascript:void(0)" class="btn btn-primary btn-xs" onclick="showModalImage('/images/measure/<?php echo $measure->getImage() ?>','<?php echo $this->config['component']['image'][1] ; ?>')"><span class="glyphicon glyphicon-search"></span></a>
        <?php endif; ?>
      </td>
      <td><?php echo $this->escapeHtml($measure->getMeaning());?></td>
      <td><?php echo $this->escapeHtml($measure->getGeneralInformation());?></td>
      <td class='column-button'>
        <a href="<?php echo $this->url('admin/measure',
          array('action'=>'edit', 'id' => $measure->getId())); ?>"><?php echo $this->config['action']['update'] ; ?></a>
<a href="<?php echo $this->url('admin/measure',
  array('action'=>'delete', 'id' => $measure->getId())); ?>"><?php echo $this->config['action']['delete'] ; ?></a>
</td>
</tr>
<?php endforeach; ?>
</tbody>
</table>
<?php echo $this->modalHelper()->image(); ?>
<?php echo $this->paginationControl($measures, 'Sliding', 'pagination',array("route" => "admin/measure")); ?>
