<?php echo $this->doctype(); ?>
<html lang="en">
<head>

	<?php echo $this->headTitle("::Kaozend::")->setAutoEscape(false) ?>
	<?php //echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!-- Le styles -->
	<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
	->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
	->prependStylesheet($this->basePath() . 'http://fonts.googleapis.com/css?family=Average+Sans')
	->prependStylesheet($this->basePath() . '/css/fonts.css')
	->prependStylesheet($this->basePath() . '/css/style.css')
	->prependStylesheet($this->basePath() . 'http://netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css')
	->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>
	<!-- Scripts -->
	<?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
	->prependFile($this->basePath() . '/js/jquery.ui.sortable.js')
	->prependFile($this->basePath() . '/js/jquery.ui.mouse.js')
	->prependFile($this->basePath() . '/js/jquery.ui.widget.js')
	->prependFile($this->basePath() . '/js/jquery.ui.core.js')
	->prependFile($this->basePath() . '/js/scripts.js')
	->prependFile($this->basePath() . '/js/number-format.js')
	->prependFile($this->basePath() . '/js/bootstrap.min.js')
	->prependFile($this->basePath() . '/js/jquery.min.js')
	?>
	<script languaje='javascript'>
		function showModal(image,title){
			$("#modalBody img").attr('src', image);
			$("#modalImageLabel").html(title);
			$("#modalImage").modal('show');
		}
	</script>
</head>
<body>
	<div class="navbar navbar-default navbar-fixed-top" role="navigation">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
				<span class="sr-only">Cambiar Navegación</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="#"><span class="glyphicon glyphicon-home"></span></a>
		</div>
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav">
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">Admin <b class="caret"></b></a>
					<ul class="dropdown-menu">
						<li><a href="/bank">Bancos</a></li>
						<li><a href="/payment-method">Metodos de Pago</a></li>
						<li class="dropdown-header">Especificaciones</li>
						<li><a href="/specification-master">Maestras</a></li>
						<li><a href="/specification">Especificaciones</a></li>
						<li class="dropdown-header">Categorias</li>
						<li><a href="/master-category">Maestra</a></li>
						<li><a href="/category">Categorias</a></li>
						<li class="dropdown-header">Medidas</li>
						<li><a href="/measure-type">Tipos de Medidas</a></li>
						<li><a href="/measure">Medidas</a></li>
						<li><a href="/serial-name">Nombre de seriales</a></li>
						<li><a href="/list-price">lista de precios</a></li>
						<li><a href="/brand">Marcas</a></li>
						<li><a href="/product">Productos</a></li>
					</ul>
				</li>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">Seguridad <b class="caret"></b></a>
					<ul class="dropdown-menu">
						<li><a href="/security/rol">Roles</a></li>
						<li><a href="/security/user">Usuarios</a></li>
					</ul>
				</li>
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-user"></span>&nbsp;<?php echo $this->identity; ?><b class="caret"></b></a>
					<ul class="dropdown-menu">
						<li><a href="#">Perfil</a></li>
						<li><a href="#">Configuración</a></li>
						<li class="divider"></li>
						<li><a href="#">Ayudanos a mejorar</a></li>
						<li><a href="#">Reportar error</a></li>
						<li class="divider"></li>
						<li><a href="<?php echo $this->url("security/logout"); ?>">Cerrar Sesión</a></li>
					</ul>
				</li>
			</ul>
		</div>
	</div>
	<div class="container">
		<div class="row">
			<div class="col-md-12"><?php echo $this->content; ?></div>
		</div>
		<br><br>
		<div class="navbar navbar-default navbar-fixed-bottom" role="navigation">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
					<span class="sr-only">Cambiar Navegación</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
			</div>
			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav navbar-right">
					<li class="active"><a href="#">No Entrada <span class="badge">42</span></a></li>
					<li class="active"><a href="#">No Salida <span class="badge">34</span></a></li>
				</ul>
			</div>
		</div>
	</div>
	<!-- /container -->
	<?php echo $this->inlineScript() ?>
</body>
</html>
