<?php echo $this->doctype(); ?>
<html lang="en">
<head>
	<?php echo $this->headTitle("::Kaozend::")->setAutoEscape(false) ?>
	<?php //echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!-- Le styles -->
	<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
	->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
	->prependStylesheet($this->basePath() . 'http://fonts.googleapis.com/css?family=Average+Sans')
	->prependStylesheet($this->basePath() . '/css/fonts.css')
	->prependStylesheet($this->basePath() . '/css/style.css')
	->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>
</head>
<body>
	<div class="container">
		<div class="row">
			<div class="col-md-3"></div>
			<div class="col-md-6"><?php echo $this->content; ?></div>
			<div class="col-md-3"></div>
		</div>
	</div>
	<?php echo $this->inlineScript() ?>
</body>
</html>
