<?php
$title = $this->config['component']['serial_name'][0];
$this->headTitle($title);
?>
<h2><?php echo $this->escapeHtml($title); ?></h2>
<p>
    <a href="<?php echo $this->url('admin/serial_name', array('action'=>'add'));?>"><?php echo $this->config['action']['add'] ; ?></a>
</p>

<table class="table table-striped table-bordered">
<tr>
    <th><?php echo $this->config['component']['name'][1] ;?></th>
    <th><?php echo $this->config['component']['description'][1] ;?></th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($serialsName as $serialName) : ?>
<tr>
    <td><?php echo $this->escapeHtml($serialName->getName());?></td>
    <td><?php echo $this->escapeHtml($serialName->getDescription());?></td>
    <td class='column-button'>
        <a href="<?php echo $this->url('admin/serial_name',
            array('action'=>'edit', 'id' => $serialName->getId())); ?>"><?php echo $this->config['action']['update'] ; ?></a>
        <a href="<?php echo $this->url('admin/serial_name',
            array('action'=>'delete', 'id' => $serialName->getId())); ?>"><?php echo $this->config['action']['delete'] ; ?></a>
    </td>
</tr>
<?php endforeach; ?>
</table>