<?php
$title = $this->config['component']['customer'][0];
echo $this->layoutHelper()->header(array(
    'module' => array('url' => $this->url('admin/customer'),'value' => $title),
    ));
    ?>
    <p>
        <a href="<?php echo $this->url('admin/customer', array('action'=>'add'));?>"><?php echo $this->config['action']['add'] ; ?></a>
    </p>
    <table class="table table-striped table-bordered">
        <tr>
            <th><?php echo $this->config['component']['identification'][1] ?></th>
            <th><?php echo $this->config['component']['identification_type'][1] ?></th>
            <th><?php echo $this->config['component']['first_name'][1] ?></th>
            <th><?php echo $this->config['component']['last_name'][1] ?></th>
            <th><?php echo $this->config['component']['company'][1] ?></th>
            <th><?php echo $this->config['component']['email'][1] ?></th>
            <th><?php echo $this->config['component']['address'][1] ?></th>
            <th><?php echo $this->config['component']['phone'][1] ?></th>
            <th>&nbsp;</th>
        </tr>
        <?php foreach ($customers as $customer) : ?>
            <tr>
                <td><?php echo $this->escapeHtml($customer->getIdentification());?></td>
                <td><?php echo $this->escapeHtml($customer->getIdentificationType());?></td>
                <td><?php echo $this->escapeHtml($customer->getFirstName());?></td>
                <td><?php echo $this->escapeHtml($customer->getLastName());?></td>
                <td><?php echo $this->escapeHtml($customer->getCompany());?></td>
                <td>
                    <?php if(count($customer->getEmails())>0) : ?>
                        <?php echo json_decode($customer->getEmails())[0];?>
                        <a href="javascript:void(0)" class="btn btn-primary btn-xs" onclick='showModalList("<?php echo addslashes($customer->getEmails()); ?>","<?php echo $this->config['component']['email'][0] ?>");'>
                            <span class="glyphicon glyphicon-th-list"></span></a>
                        <?php endif; ?>
                    </td>
                    <td>
                        <?php if(count($customer->getEmails())>0) : ?>
                            <?php echo json_decode($customer->getAddresses())[0];?>
                            <a href="javascript:void(0)" class="btn btn-primary btn-xs" onclick='showModalList("<?php echo addslashes($customer->getAddresses()); ?>","<?php echo $this->config['component']['address'][0] ?>");'>
                                <span class="glyphicon glyphicon-th-list"></span></a>
                            <?php endif; ?>
                        </td>
                        <td>
                            <?php if(count($customer->getEmails())>0) : ?>
                                <?php echo json_decode($customer->getPhones())[0];?>
                                <a href="javascript:void(0)" class="btn btn-primary btn-xs" onclick='showModalList("<?php echo addslashes($customer->getPhones()); ?>","<?php echo $this->config['component']['phone'][0] ?>");'>
                                    <span class="glyphicon glyphicon-th-list"></span></a>
                                <?php endif;?>
                            </td>
                            <td class='column-button'>
                                <a href="<?php echo $this->url('admin/customer',
                                    array('action'=>'edit', 'id' => $customer->getId())); ?>"><?php echo $this->config['action']['update'] ; ?></a>
<a href="<?php echo $this->url('admin/customer',
    array('action'=>'delete', 'id' => $customer->getId())); ?>"><?php echo $this->config['action']['delete'] ; ?></a>
</td>
</tr>
<?php endforeach; ?>
</table>
<?php echo $this->modalHelper()->listContent(); ?>
<?php echo $this->paginationControl($customers, 'Sliding', 'pagination',array("route" => "admin/customer")); ?>
