<?php
$title = $this->config['component']['list_price'][0];
$this->headTitle($title);
?>
<h2><?php echo $this->escapeHtml($title); ?></h2>
<p>
    <a href="<?php echo $this->url('admin/list_price', array('action'=>'add'));?>"><?php echo $this->config['action']['add'] ; ?></a>
</p>


<table class="table table-striped table-bordered">
<tr>
    <th><?php echo $this->config['component']['name'][1] ?></th>
    <th><?php echo $this->config['component']['description'][1] ?></th>
    <th><?php echo $this->config['component']['principal'][1] ?></th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($listPrices as $listPrice) : ?>
<tr>
    <td><?php echo $this->escapeHtml($listPrice->getName());?></td>
    <td><?php echo $this->escapeHtml($listPrice->getDescription());?></td>
    <td><?php echo $listPrice->getPrincipal()==1 ? "Activa" : "Inactiva";?></td>
    <td class='column-button'>
        <a href="<?php echo $this->url('admin/list_price',
            array('action'=>'edit', 'id' => $listPrice->getId())); ?>"><?php echo $this->config['action']['update'] ; ?></a>
        <a href="<?php echo $this->url('admin/list_price',
            array('action'=>'delete', 'id' => $listPrice->getId())); ?>"><?php echo $this->config['action']['delete'] ; ?></a>
    </td>
</tr>
<?php endforeach; ?>
</table>