<?php
$title = $this->config['component']['list_price'][0];
$action = $this->config['action']['create']['text'];
echo $this->layoutHelper()->header(array(
    'module' => array('url' => $this->url('admin/list_price'),'value' => $title),
    ));
    ?>
    <p>
        <a href="<?php echo $this->url('admin/list_price', array('action'=>'add'));?>"><label class="<?php echo $this->config['action']['create']['class']; ?>"><i class="<?php echo $this->config['action']['create']['icon']; ?>"></i><?php echo $action ?></label></a>
    </p>


    <table class="table table-striped table-bordered" id='dataTable'>
        <thead>
            <tr>
                <th><?php echo $this->config['component']['name'][1] ?></th>
                <th><?php echo $this->config['component']['description'][1] ?></th>
                <th><?php echo $this->config['component']['principal'][1] ?></th>
                <th>&nbsp;</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($listPrices as $listPrice) : ?>
                <tr>
                    <td><?php echo $this->escapeHtml($listPrice->getName());?></td>
                    <td><?php echo $this->escapeHtml($listPrice->getDescription());?></td>
                    <td><?php echo $listPrice->getPrincipal()==1 ? "Activa" : "Inactiva";?></td>
                    <td class='column-button'>
                        <a href="<?php echo $this->url('admin/list_price',
                            array('action'=>'edit', 'id' => $listPrice->getId())); ?>"><label class="<?php echo $this->config['action']['update']['class']; ?>">
                                <i class="<?php echo $this->config['action']['update']['icon'] ; ?>"></i>
                            </label></a>
<a href="<?php echo $this->url('admin/list_price',
    array('action'=>'delete', 'id' => $listPrice->getId())); ?>"><label class="<?php echo $this->config['action']['delete']['class']; ?>">
                                <i class="<?php echo $this->config['action']['delete']['icon'] ; ?>"></i>
                            </label></a>
</td>
</tr>
<?php endforeach; ?>
</tbody>
</table>
<?php echo $this->paginationControl($listPrices, 'Sliding', 'pagination',array("route" => "admin/list_price")); ?>
