<?php
$title = $this->config['component']['category'][0];
$action = $this->config['action']['new'];
echo $this->layoutHelper()->header(array(
	'module' => array('url' => $this->url('admin/category'),'value' => $title),
	'action' => array('url' => '','value' => $action)
	));
	?>
	<?php echo $this->formElementErrors($form->get('specification'), array("class" => "error")); ?>
	<?php $form = $this->form; ?>
	<?php $form->setAttribute('action', $this->url('admin/category', array('action' => 'add'))); ?>
	<?php $form->prepare(); ?>
	<?php echo $this->form()->openTag($form); ?>
	<div class="form-group">
		<?php echo $this->formLabel($form->get('master_category')->setLabel($this->config['component']['master_category'][1])); ?>
		<div class="col-sm-5">
			<?php echo $this->formHidden($form->get('id')); ?>
			<?php echo $this->formHidden($form->get('csrf'));?>
			<?php echo $this->formSelect($form->get('master_category')); ?>
			<?php echo $this->formElementErrors($form->get('master_category'), array("class" => "error")); ?>
		</div>
	</div>
	<div class="form-group">
		<?php echo $this->formLabel($form->get('singular_name')->setLabel($this->config['component']['singular_name'][1])); ?>
		<div class="col-sm-5">
			<?php echo $this->formInput($form->get('singular_name')); ?>
			<?php echo $this->formElementErrors($form->get('singular_name'), array("class" => "error")); ?>
		</div>
	</div>
	<div class="form-group">
		<?php echo $this->formLabel($form->get('plural_name')->setLabel($this->config['component']['plural_name'][1])); ?>
		<div class="col-sm-5">
			<?php echo $this->formInput($form->get('plural_name')); ?>
			<?php echo $this->formElementErrors($form->get('plural_name'), array("class" => "error")); ?>
		</div>
	</div>
	<div class="form-group">
		<?php echo $this->formLabel($form->get('image')); ?>
		<div class="col-sm-5">
			<?php echo $this->formInput($form->get('image')); ?>
			<?php echo $this->formElementErrors($form->get('image'), array("class" => "error")); ?>
			<p class="help-block">
				Extensiones Permitidas: <?php echo implode($this->config['file_characteristics']['image']['extension'],',') ;?><br>
				Tama&ntilde;o: 
				<?php foreach($this->config['file_characteristics']['image']['size'] as $range => $size): ?>
					<?php echo $range." ".$size ; ?>
				<?php endforeach; ?>
			</p>
		</div>
	</div>
	<div class="form-group">
		<?php echo $this->formLabel($form->get('shipping_cost')->setLabel($this->config['component']['shipping_cost'][1])); ?>
		<div class="col-sm-3">
			<div class="input-group">
				<span class="input-group-addon">$</span>
				<?php echo $this->formInput($form->get('shipping_cost')); ?>
				<span class="input-group-addon">.00</span>
			</div>
			<?php echo $this->formElementErrors($form->get('shipping_cost'), array("class" => "error")); ?>
		</div>
	</div>
	<div class="form-group">
		<?php echo $this->formLabel($form->get('additional_shipping')->setLabel($this->config['component']['additional_shipping'][1])); ?>
		<div class="col-sm-3">
			<div class="input-group">
				<span class="input-group-addon">$</span>
				<?php echo $this->formInput($form->get('additional_shipping')); ?>
				<span class="input-group-addon">.00</span>
			</div>
			<?php echo $this->formElementErrors($form->get('additional_shipping'), array("class" => "error")); ?>
		</div>
	</div>
	<div class="form-group">
		<?php echo $this->formLabel($form->get('description')->setLabel($this->config['component']['description'][1])); ?>
		<div class="col-sm-6">
			<?php echo $this->formTextarea($form->get('description')); ?>
			<?php echo $this->formElementErrors($form->get('description'), array("class" => "error")); ?>
		</div>
	</div>
	<div class="form-group">
		<?php echo $this->formLabel($form->get('serial_name')->setLabel($this->config['component']['serial_name'][0])); ?>
		<div class="col-sm-6">
			<?php echo $this->formSelect($form->get('serial_name')); ?>
			<?php echo $this->formElementErrors($form->get('serial_name'), array("class" => "error")); ?>
		</div>
	</div>
	<h4 class="page-header"><?php echo $this->config['component']['specification'][0]; ?></h4>
		<div class="list-group">
			<ul id="sortable">
				<?php $formMultiCheckbox = $this->formMultiCheckbox(); ?>
				<?php $formMultiCheckbox->setSeparator('</li><li class="list-group-item">'.$this->config['action']['icons']['move'].'&nbsp;'); ?>
				<li class="list-group-item"><?php echo $this->config['action']['icons']['move'] ; ?>&nbsp;<?php echo $formMultiCheckbox->render($form->get('specification')); ?></li>
			</ul>
		</div>
		<div class="well well-sm">
			<?php echo $this->formSubmit($form->get('submit')->setValue($this->config['action']['create'])); ?>
			&nbsp;
			<a href="<?php echo $this->url('admin/category'); ?>"><?php echo $this->config['action']['return'] ; ?> </a>
		</div>
		<?php echo $this->form()->closeTag(); ?>
