<?php
$title = $this->config['component']['category'][0];
$action = $this->config['action']['create']['text'];
echo $this->layoutHelper()->header(array(
    'module' => array('url' => $this->url('admin/category'),'value' => $title),
    ));
    ?>
    <p>
        <a href="<?php echo $this->url('admin/category', array('action'=>'add'));?>"><label class="<?php echo $this->config['action']['create']['class']; ?>"><i class="<?php echo $this->config['action']['create']['icon']; ?>"></i><?php echo $action ?></label></a>
    </p>

    <table class="table table-striped table-bordered" id='dataTable'>
        <thead>
            <tr>
                <th><?php echo $this->config['component']['master_category'][1] ;?></th>
                <th><?php echo $this->config['component']['singular_name'][1] ;?></th>
                <th><?php echo $this->config['component']['plural_name'][1] ;?></th>
                <th><?php echo $this->config['component']['image'][1] ;?></th>	
                <th><?php echo $this->config['component']['shipping_cost'][1] ;?></th>
                <th><?php echo $this->config['component']['additional_shipping'][1] ;?></th>
                <th>&nbsp;</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($categories as $category) : ?>
                <tr>
                    <td><?php echo $this->escapeHtml($category->getMasterCategoryName());?></td>
                    <td><?php echo $this->escapeHtml($category->getSingularName());?></td>
                    <td><?php echo $this->escapeHtml($category->getPluralName());?></td>
                    <td>
                        <?php if($category->getImage()): ?>
                            <a href="javascript:void(0)" class="btn btn-primary btn-xs" onclick="showModalImage('/images/category/<?php echo $category->getImage() ?>','<?php echo $this->config['component']['image'][1] ; ?>')"><i class="<?php echo $this->config['action']['image']['icon'] ; ?>"></i></a>
                        <?php endif; ?>
                    </td>
                    <td><?php echo "$ ".number_format($category->getShippingCost());?></td>
                    <td><?php echo "$ ".number_format($category->getAdditionalShipping());?></td>
                    <td class='column-button'>
                        <a href="<?php echo $this->url('admin/category',
                            array('action'=>'edit', 'id' => $category->getId())); ?>"><label class="<?php echo $this->config['action']['update']['class']; ?>">
                                <i class="<?php echo $this->config['action']['update']['icon'] ; ?>"></i>
                            </label></a>
<a href="<?php echo $this->url('admin/category',
    array('action'=>'delete', 'id' => $category->getId())); ?>"><label class="<?php echo $this->config['action']['delete']['class']; ?>">
                                <i class="<?php echo $this->config['action']['delete']['icon'] ; ?>"></i>
                            </label></a>
</td>
</tr>
<?php endforeach; ?>
</tbody>
</table>
<?php echo $this->modalHelper()->image(); ?>
<?php echo $this->paginationControl($categories, 'Sliding', 'pagination',array("route" => "admin/category")); ?>
