<?php
$title = $this->config['component']['app'][0];
$this->headTitle($title);
?>
<h2 class="page-header"><?php echo $title ; ?></h2>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
	'admin/app',
	array(
		'action' => 'edit',
		'id'     => $this->id,
		)
	));
	$form->prepare();?>
	<?php echo $this->form()->openTag($form); ?>
	<?php echo $this->formHidden($form->get('id')); ?>
	<?php echo $this->formHidden($form->get('csrf'));?>

	<div class="form-group">
		<?php echo $this->formLabel($form->get('name')->setLabel($this->config['component']['name'])); ?>
		<div class="col-sm-4">
			<?php echo $this->formInput($form->get('name')); ?>
			<?php echo $this->formElementErrors($form->get('name'), array("class" => "error")); ?>
		</div>
	</div>
	<div class="form-group">
		<?php echo $this->formLabel($form->get('image')->setLabel($this->config['component']['image'])); ?>
		<div class="col-sm-4">
			<?php if($image): ?>
				<a href="javascript:void(0)" class="btn btn-primary btn-xs" onclick="showModalImage('/images/app/<?php echo $image; ?>','<?php echo $this->config['component']['image'][1] ; ?>')">
					<span class="glyphicon glyphicon-search"></span>
				</a>
			<?php endif; ?>
			<div class='pull-left'>
			<?php echo $this->formInput($form->get('image')); ?>
			<?php echo $this->formElementErrors($form->get('image'), array("class" => "error")); ?>
			</div>
			<p class="help-block">
				Extensiones Permitidas: <?php echo implode($this->config['file_characteristics']['image']['extension'],',') ;?><br>
				Tama&ntilde;o: 
				<?php foreach($this->config['file_characteristics']['image']['size'] as $range => $size): ?>
					<?php echo $range." ".$size ; ?>
				<?php endforeach; ?>
			</p>
		</div>
	</div>
	<div class="form-group">
		<?php echo $this->formLabel($form->get('description')->setLabel($this->config['component']['description'])); ?>
		<div class="col-sm-6">
			<?php echo $this->formTextarea($form->get('description')); ?>
		</div>
	</div>
	<?php echo $this->formSubmit($form->get('submit')->setValue($this->config['action']['edit'])); ?>
	&nbsp;<a href="<?php echo $this->url('admin/app');?>"><?php echo $this->config['action']['return'] ; ?></a>
	<?php echo $this->form()->closeTag(); ?>
	<?php echo $this->modalHelper()->image(); ?>