<?php
$title = $this->config['component']['app'][0];
$action = $this->config['action']['create']['text'];
echo $this->layoutHelper()->header(array(
    'module' => array('url' => $this->url('admin/app'),'value' => $title),
    ));
    ?>
    <p>
        <a href="<?php echo $this->url('admin/app', array('action'=>'add'));?>">
            <label class="<?php echo $this->config['action']['create']['class']; ?>"><i class="<?php echo $this->config['action']['create']['icon']; ?>"></i><?php echo $action; ?></label>
        </a>
    </p>
    <table class="table table-striped table-bordered" id='dataTable'>
        <thead>
            <tr>
                <th><?php echo $this->config['component']['name'][1] ?></th>
                <th><?php echo $this->config['component']['description'][1] ?></th>
                <th><?php echo $this->config['component']['image'][1] ?></th>
                <th>&nbsp;</th>
            </tr>
        </thead>
        <tboby>
            <?php foreach ($apps as $app) : ?>
                <tr>
                    <td><?php echo $this->escapeHtml($app->getName());?></td>
                    <td><?php echo $this->escapeHtml($app->getDescription());?></td>
                    <td>
                        <?php if($app->getImage()): ?>
                            <a href="javascript:void(0)" class="<?php echo $this->config['action']['image']['class']; ?>" onclick="showModalImage('/images/app/<?php echo $app->getImage() ?>','<?php echo $this->config['component']['image'][1] ; ?>')"><i class="<?php echo $this->config['action']['image']['icon'] ; ?>"></i></a>
                        <?php endif; ?>
                    </td>
                    <td class='column-button'>
                        <a href="<?php echo $this->url('admin/app', array('action'=>'edit', 'id' => $app->getId())); ?>">
                            <label class="<?php echo $this->config['action']['update']['class']; ?>">
                                <i class="<?php echo $this->config['action']['update']['icon'] ; ?>"></i>
                            </label></a>
                            <a href="<?php echo $this->url('admin/app', array('action'=>'delete', 'id' => $app->getId())); ?>">
                                <label class="<?php echo $this->config['action']['delete']['class']; ?>">
                                   <i class="<?php echo $this->config['action']['delete']['icon'] ; ?>"></i>
                               </label>
                           </a>
                       </td>
                   </tr>
               <?php endforeach; ?>
           </tboby>
       </table>
       <?php echo $this->modalHelper()->image(); ?>
       <?php echo $this->paginationControl($apps, 'Sliding', 'pagination',array("route" => "admin/app")); ?>