<?php
$title = $this->config['component']['master_category'][0];
$this->headTitle($title);
?>
<h2 class="page-header"><?php echo $title ; ?></h2>
<?php $form = $this->form; ?>
<?php $form->setAttribute('action', $this->url('admin/master_category', array('action' => 'add'))); ?>
<?php $form->prepare(); ?>
<?php echo $this->form()->openTag($form); ?>
<?php echo $this->formHidden($form->get('id')); ?>
<?php echo $this->formHidden($form->get('csrf')); ?>
<div class="form-group">
	<div class="col-lg-4">
		<?php echo $this->formLabel($form->get('name')->setLabel($this->config['component']['name'][1])); ?>
		<?php echo $this->formInput($form->get('name')); ?>
		<?php echo $this->formElementErrors($form->get('name'), array("class" => "error")); ?>
	</div>
	<div class="form-group">
		<div class="col-lg-4">
			<?php echo $this->formLabel($form->get('image')->setLabel($this->config['component']['image'][1])); ?>
			<?php echo $this->formInput($form->get('image')); ?>
			<?php echo $this->formElementErrors($form->get('image'), array("class" => "error")); ?>
			<p class="help-block">
				Extensiones Permitidas: <?php echo implode($this->config['file_characteristics']['image']['extension'],',') ;?><br>
				Tama&ntilde;o: 
				<?php foreach($this->config['file_characteristics']['image']['size'] as $range => $size): ?>
					<?php echo $range." ".$size ; ?>
				<?php endforeach; ?>
			</p>
		</div>
	</div>
	<div class="form-group">
		<div class="col-lg-6">
			<?php echo $this->formLabel($form->get('description')->setLabel($this->config['component']['description'][1])); ?>
			<?php echo $this->formTextarea($form->get('description')); ?>
			<?php echo $this->formElementErrors($form->get('description'), array("class" => "error")); ?>
		</div>
	</div>
	<?php echo $this->formSubmit($form->get('submit')->setValue($this->config['action']['create'])); ?>
	&nbsp;
	<a href="<?php echo $this->url('admin/master_category'); ?>"><?php echo $this->config['action']['return'] ; ?> </a>
	<?php echo $this->form()->closeTag(); ?>