<?php
$title = $this->config['component']['master_category'][0];
$action = $this->config['action']['create']['text'];
echo $this->layoutHelper()->header(array(
	'module' => array('url' => $this->url('admin/master_category'),'value' => $title),
	'action' => array('url' => '','value' => $action)
	));
	?>
<?php if(isset($error) && $error): ?>
	<div class="alert alert-danger fade in">
		<h4 class='clear-text'>¡Vaya! Se ha producido un error.</h4>
		<p>No se puede borrar el registro de <?php echo $title; ?> ya que este se encuentra vinculado a otro registro.</p>
		<p>
			<a href="<?php echo $this->url('admin/master_category');?>"><label class="<?php echo $this->config['action']['return']['class']; ?>">
<i class="<?php echo $this->config['action']['return']['icon'] ; ?>"></i>
<?php echo $this->config['action']['return']['text']; ?>
</label> </a>
		</p>
	</div>
<?php else: ?>
	<div class="alert alert-danger">
		<p>Esta seguro que quiere borrar '<?php echo $this->escapeHtml($masterCategory->getName()); ?>'?</p>
	</div>
	<?php
	$url = $this->url('admin/master_category', array(
		'action' => 'delete',
		'id'=> $this->id,
		));
		?>
		<form action="<?php echo $url; ?>" method="post">
			<div class="well well-sm">
				<input type="hidden" name="id" value="<?php echo (int) $masterCategory->getId(); ?>" />
				<input type="submit" name="del" value="Si" class="btn btn-danger btn-sm"/>
				<input type="submit" name="del" value="No" class="btn btn-default btn-sm"/>
			</div>
		</form>
	<?php endif; ?>
