<?php
$title = $this->config['component']['master_category'][0];
$action = $this->config['action']['new'];
echo $this->layoutHelper()->header(array(
    'module' => array('url' => $this->url('admin/master_category'),'value' => $title),
    ));
    ?>
    <p>
        <a href="<?php echo $this->url('admin/master_category', array('action'=>'add'));?>"><?php echo $this->config['action']['add'] ; ?></a>
    </p>
    <table class="table table-striped table-bordered" id='dataTable'>
        <thead>
            <tr>
                <th><?php echo $this->config['component']['name'][1] ?></th>
                <th><?php echo $this->config['component']['description'][1] ?></th>
                <th><?php echo $this->config['component']['image'][1] ?></th>
                <th>&nbsp;</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($masterCategories as $masterCategory) : ?>
                <tr>
                    <td><?php echo $this->escapeHtml($masterCategory->getName());?></td>
                    <td><?php echo $this->escapeHtml($masterCategory->getDescription());?></td>
                    <td>
                        <?php if($masterCategory->getImage()): ?>
                            <a href="javascript:void(0)" class="btn btn-primary btn-xs" onclick="showModalImage('/images/master_category/<?php echo $masterCategory->getImage() ?>','<?php echo $this->config['component']['image'][1] ; ?>')"><span class="glyphicon glyphicon-search"></span></a>
                        <?php endif; ?>
                    </td>
                    <td class='column-button'>
                        <a href="<?php echo $this->url('admin/master_category',
                            array('action'=>'edit', 'id' => $masterCategory->getId())); ?>"><?php echo $this->config['action']['update'] ; ?></a>
<a href="<?php echo $this->url('admin/master_category',
    array('action'=>'delete', 'id' => $masterCategory->getId())); ?>"><?php echo $this->config['action']['delete'] ; ?></a>
</td>
</tr>
<?php endforeach; ?>
</tbody>
</table>
<?php echo $this->modalHelper()->image(); ?>
<?php echo $this->paginationControl($masterCategories, 'Sliding', 'pagination',array("route" => "admin/master_category")); ?>
