<?php $form = $this->form; ?>
<?php $form->setAttribute('action', $this->url('security/login')); ?>
<?php $form->prepare(); ?>
<?php echo $this->form()->openTag($form); ?>
<div class="form-group">
   <div class="col-lg-6">
      <?php echo $this->formHidden($form->get('csrf')); ?>
      <?php echo $this->formLabel($form->get('username')->setLabel($this->config['component']['username'][1])); ?>
      <?php echo $this->formInput($form->get('username')); ?>
      <?php echo $this->formElementErrors($form->get('username'), array("class" => "error")); ?>
   </div>
</div>
<div class="form-group">
   <div class="col-lg-6">
      <?php echo $this->formLabel($form->get('password')->setLabel($this->config['component']['password'][1])); ?>
      <?php echo $this->formInput($form->get('password')); ?>
      <?php echo $this->formElementErrors($form->get('password'), array("class" => "error")); ?>
   </div>
</div>
<div class="form-group">
   <div class="col-lg-6">
      <?php echo $this->formSubmit($form->get('submit')->setValue($this->config['action']['login'])); ?>
   </div>
</div>
<?php echo $this->form()->closeTag(); ?>
