<?php
$title = $this->config['component']['specification_master'][0];
$action = $this->config['action']['edit'];
echo $this->layoutHelper()->header(array(
	'module' => array('url' => $this->url('admin/specification_master'),'value' => $title),
	'action' => array('url' => '','value' => $action)
	));
	?>
	<?php
	$form = $this->form;
	$form->setAttribute('action', $this->url(
		'admin/specification_master',
		array(
			'action' => 'edit',
			'id'     => $this->id,
			)
		));
		$form->prepare();?>
		<?php echo $this->form()->openTag($form); ?>
		<?php echo $this->formHidden($form->get('id')); ?>
		<?php echo $this->formHidden($form->get('csrf'));?>
		<div class="form-group">
			<?php echo $this->formLabel($form->get('name')->setLabel($this->config['component']['name'][1])); ?>
			<div class="col-sm-4">
				<?php echo $this->formInput($form->get('name')); ?>
				<?php echo $this->formElementErrors($form->get('name'), array("class" => "error")); ?>
			</div>
		</div>
		<div class="form-group">
			<?php echo $this->formLabel($form->get('image')->setLabel($this->config['component']['image'][1])); ?>
			<div class="col-sm-4">
				<?php if($image): ?>
					<a href="javascript:void(0)" class="btn btn-primary btn-xs" onclick="showModalImage('/images/specificacion-master/<?php echo $image ?>','<?php echo $this->config['component']['image'][1] ; ?>')"><span class="glyphicon glyphicon-search"></span></a>
				<?php endif; ?>
				<div class='pull-left'>
					<?php echo $this->formInput($form->get('image')); ?>
					<?php echo $this->formElementErrors($form->get('image'), array("class" => "error")); ?>
				</div>
				<p class="help-block">
					Extensiones Permitidas: <?php echo implode($this->config['file_characteristics']['image']['extension'],',') ;?><br>
					Tama&ntilde;o:
					<?php foreach($this->config['file_characteristics']['image']['size'] as $range => $size): ?>
						<?php echo $range." ".$size ; ?>
					<?php endforeach; ?>
				</p>
			</div>
		</div>
		<div class="form-group">
			<?php echo $this->formLabel($form->get('description')->setLabel($this->config['component']['description'][1])); ?>
			<div class="col-sm-6">
				<?php echo $this->formTextarea($form->get('description')); ?>
			</div>
		</div>
		<div class="well well-sm">
			<?php echo $this->formSubmit($form->get('submit')->setValue($this->config['action']['edit'])); ?>
			&nbsp;<a href="<?php echo $this->url('admin/specification_master');?>"><?php echo $this->config['action']['return'] ; ?></a>
		</div>
		<?php echo $this->form()->closeTag(); ?>