<?php
$title = $this->config['component']['specification_master'][0];
$action = $this->config['action']['new'];
echo $this->layoutHelper()->header(array(
    'module' => array('url' => $this->url('admin/specification_master'),'value' => $title),
    ));
    ?>
    <p>
        <a href="<?php echo $this->url('admin/specification_master', array('action'=>'add'));?>"><?php echo $this->config['action']['add'] ; ?></a>
    </p>


    <table class="table table-striped table-bordered">
        <thead>
            <tr>
                <th><?php echo $this->config['component']['name'][1] ?></th>
                <th><?php echo $this->config['component']['description'][1] ?></th>
                <th><?php echo $this->config['component']['image'][1] ?></th>
                <th>&nbsp;</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($specificationsMasters as $specificationMaster) : ?>
                <tr>
                    <td><?php echo $this->escapeHtml($specificationMaster->getName());?></td>
                    <td><?php echo $this->escapeHtml($specificationMaster->getDescription());?></td>
                    <td>
                       <?php if($specificationMaster->getImage()): ?>
                        <a href="javascript:void(0)" class="btn btn-primary btn-xs" onclick="showModalImage('/images/specification_master/<?php echo $specificationMaster->getImage() ?>','<?php echo $this->config['component']['image'][1] ; ?>')"><span class="glyphicon glyphicon-search"></span></a>
                    <?php endif; ?>
                </td>
                <td class='column-button'>
                    <a href="<?php echo $this->url('admin/specification_master',
                        array('action'=>'edit', 'id' => $specificationMaster->getId())); ?>"><?php echo $this->config['action']['update'] ; ?></a>
<a href="<?php echo $this->url('admin/specification_master',
    array('action'=>'delete', 'id' => $specificationMaster->getId())); ?>"><?php echo $this->config['action']['delete'] ; ?></a>
</td>
</tr>
<?php endforeach; ?>
</tbody>
</table>
<?php echo $this->modalHelper()->image(); ?>
<?php echo $this->paginationControl($specificationsMasters, 'Sliding', 'pagination',array("route" => "admin/specification_master")); ?>
