<?php
$title = $this->config['component']['product'][0];
$this->headTitle($title);
?>
<h2>
	<?php echo $this->escapeHtml($title); ?>
</h2>
<div class="alert alert-danger">
<p>Esta seguro que quiere borrar '<?php echo $this->escapeHtml($product->getUpcBarCode()." - ".$product->getModel()); ?>'?</p>
</div>
<?php
$url = $this->url('product', array(
		'action' => 'delete',
		'id'=> $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
	<div>
		<input type="hidden" name="id"
			value="<?php echo (int) $product->getId(); ?>" />
			<input type="submit" name="del" value="Si" />
			<input type="submit" name="del" value="No" />
	</div>
</form>