<?php
$title = $this->config['component']['product'][0];
$this->headTitle($title);
?>
<h2 class="page-header"><?php echo $title ; ?></h2>
<p>
    <a href="<?php echo $this->url('admin/product', array('action'=>'add'));?>"><?php echo $this->config['action']['add'] ; ?></a>
</p>

<table class="table table-striped table-bordered table-hover">
<tr>
    <th><?php echo $this->config['component']['upc_bar_code'][1] ;?></th>
    <th><?php echo $this->config['component']['model'][1] ;?></th>
    <th><?php echo $this->config['component']['brand'][1] ;?></th>
    <th><?php echo $this->config['component']['category'][1] ;?></th>
    <th><?php echo $this->config['component']['price'][1] ;?></th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($products as $product) : ?>
<tr>
    <td><?php echo $this->escapeHtml($product->getUpcBarCode());?></td>
    <td><?php echo $this->escapeHtml($product->getModel());?></td>
    <td><?php echo $this->escapeHtml($product->getBrandName());?></td>
    <td><?php echo $this->escapeHtml($product->getCategoryName());?></td>
    <td><?php echo $this->escapeHtml($product->getPrice());?></td>
    <td class='column-button'>
        <a href="<?php echo $this->url('admin/product',
            array('action'=>'edit', 'id' => $product->getId())); ?>"><?php echo $this->config['action']['update'] ; ?></a>
        <a href="<?php echo $this->url('admin/product',
            array('action'=>'delete', 'id' => $product->getId())); ?>"><?php echo $this->config['action']['delete'] ; ?></a>
    </td>
</tr>
<?php endforeach; ?>
</table>