<?php echo $this->doctype(); ?>
<html lang="en">
<head>

	<?php echo $this->headTitle("::Kaozend::")->setAutoEscape(false) ?>
	<?php //echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!-- Le styles -->
	<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
	->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
	->prependStylesheet($this->basePath() . 'http://fonts.googleapis.com/css?family=Average+Sans')
	->prependStylesheet($this->basePath() . '/css/fonts.css')
	->prependStylesheet($this->basePath() . '/css/style.css')
	->prependStylesheet($this->basePath() . 'http://netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css')
	->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>
	<!-- Scripts -->
	<?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
	->prependFile($this->basePath() . '/js/functions.js')
	->prependFile($this->basePath() . '/js/jquery.ui.sortable.js')
	->prependFile($this->basePath() . '/js/jquery.ui.mouse.js')
	->prependFile($this->basePath() . '/js/jquery.ui.widget.js')
	->prependFile($this->basePath() . '/js/jquery.ui.core.js')
	->prependFile($this->basePath() . '/js/bootstrap.min.js')
	->prependFile($this->basePath() . '/js/jquery.min.js')
	?>
</head>
<body>
	<div class="navbar-inverse navbar-default navbar-fixed-top" role="navigation">
		<div class="navbar-header">
			<div class='pull-left'><img src='/img/logo.png'></div>
		</div>
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<!--<form class="navbar-form navbar-right" role="search">
				<div class="form-group">
					<input type="text" class="form-control" placeholder="Usuario">
				</div>
				<div class="form-group">
					<input type="password" class="form-control" placeholder="Contraseña">
				</div>
				<button type="submit" class="btn btn-default">Ingresar</button>
			</form>
			-->
		</div>
	</div>
	<div class="container">
		<div class="row">
			<div class="col-md-12"><?php echo $this->content; ?></div>
		</div>
	</div>
</div>
<?php echo $this->inlineScript() ?>
</body>
</html>
