<?php
return array(
	'component' => array(
		'abbreviation' 			=> array('abreviaciones', 'abreviación'),
		'additional_shipping' 	=> array('envios adicionales','envio adicional'),
		'background_image' 		=> array('imagenes de fondo','imagen de fondo'),
		'bank' 					=> array('bancos','banco'),
		'bank_info' 			=> array('informaciones de banco','información de banco'),
		'brand' 				=> array('marcas','marca','image_path'=> 'public/images/brand'),		
		'category' 				=> array('categorias','categoria','image_path'=> 'public/images/category'),
		'description' 			=> array('descripciones','descripción'),
		'email' 				=> array('emails','email'),
		'file' 					=> array('archivos','archivo'),
		'general_information' 	=> array('información general','información general'),
		'image' 				=> array('imagenes','imagen'),
		'iva' 					=> array('ivas','iva'),
		'list_price' 			=> array('listas de precios','lista de precio'),
		'login' 				=> array('ingresar','ingresar'),
		'manual_file'			=> array('archivos de manuales','archivo manual'),
		'master_category' 		=> array('categorias maestras','categoria maestra','image_path'=> 'public/images/master_category'),
		'measure' 				=> array('medidas','medida','image_path'=> 'public/images/measure'),
		'measure_value' 		=> array('valor de medidas','valor de medida'),
		'measure_type' 			=> array('tipos de medidas','tipo de medida'),
		'meaning' 				=> array('significados','significado'),
		'model' 				=> array('modelos','modelo'),
		'name' 					=> array('nombres','nombre'),
		'no_part' 				=> array('no partes','no parte'),
		'password' 				=> array('contraseñas','contraseña'),
		'payment_method' 		=> array('metodos de pago','metodo de pago'),
		'plural_name' 			=> array('nombres plural','nombre plural'),
		'price' 				=> array('precios','precio'),
		'principal' 			=> array('principales','principal'),
		'product' 				=> array('productos','producto','image_path'=> 'public/images/product','file_path'=> 'public/files/product','video_path'=> 'public/videos/product'),
		'qty_buy' 				=> array('cantidades comprar','cantidad comprar'),
		'qty_low' 				=> array('cantidades minimas','cantidad minima'),
		'rol' 					=> array('roles','rol'),
		'serial_name' 			=> array('seriales','serial'),
		'shipping_cost' 		=> array('costos de envio','costo de envio'),
		'singular_name' 		=> array('nombres singular','nombre singular'),
		'specification' 		=> array('especificaciones','espeficación','image_path'=> 'public/images/specification'),
		'specification_file'	=> array('archivos de especificaciones','archivo especificación'),
		'specification_master' 	=> array('especificaciones maestras','espeficación maestra','image_path'=> 'public/images/specification_master'),
		'status' 				=> array('estados','estado'),
		'video' 				=> array('videos','video'),
		'username'				=> array('nombres de usuario','nombre de usuario'),
		'upc_bar_code'			=> array('codigos UPC', 'codigo UPC')
		)
);
?>