<?php
return array(
	'component' => array(
		'abbreviation' 			=> array('abreviaciones', 'abreviación'),
		'additional_shipping' 	=> array('envios adicionales','envio adicional'),
		'address' 				=> array('direcciones','dirección'),
		'alias' 				=> array('alias','alias'),
		'app' 					=> array('aplicaciones','aplicación','image_path'=> 'public/images/app'),
		'authorized' 			=> array('autorizaciones','autorización'),
		'background_image' 		=> array('imagenes fondo','imagen fondo'),
		'bank' 					=> array('bancos','banco'),
		'bank_info' 			=> array('informaciones banco','información banco'),
		'birthday' 				=> array('cumpleaños','cumpleaños'),
		'brand' 				=> array('marcas','marca','image_path'=> 'public/images/brand'),
		'category' 				=> array('categorias','categoria','image_path'=> 'public/images/category'),
		'classification'		=> array('clasificaciones','clasificatión'),
		'company' 				=> array('compañias','compañia'),
		'customer' 				=> array('clientes','cliente'),
		'city' 					=> array('ciudades','ciudad'),
		'description' 			=> array('descripciones','descripción'),
		'document' 				=> array('documentos','documento'),
		'email' 				=> array('emails','email'),
		'file' 					=> array('archivos','archivo'),
		'first_name'			=> array('nombres','nombres'),
		'general_information' 	=> array('información general','información general'),
		'guide_number' 			=> array('guias','guia'),
		'identification'		=> array('identificaciones','identificación'),
		'identification_type'	=> array('tipos identificaciones','tipo identificación'),
		'image' 				=> array('imagenes','imagen'),
		'invoice' 				=> array('entradas','entrada'),
		'invoice_file' 			=> array('entradas archivo','entrada archivo'),
		'iva' 					=> array('ivas','iva'),
		'last_name' 			=> array('apellidos','apellidos'),
		'list_price' 			=> array('listas precios','lista precio'),
		'login' 				=> array('ingresar','ingresar'),
		'manager'				=> array('gerentes','gerente'),
		'manual_file'			=> array('archivos manuales','archivo manual'),
		'master_category' 		=> array('categorias maestras','categoria maestra','image_path'=> 'public/images/master_category'),
		'measure' 				=> array('medidas','medida','image_path'=> 'public/images/measure'),
		'measure_value' 		=> array('valor medidas','valor medida'),
		'measure_type' 			=> array('tipos medidas','tipo medida'),
		'meaning' 				=> array('significados','significado'),
		'model' 				=> array('modelos','modelo'),
		'module' 				=> array('modulos','modulo'),
		'name' 					=> array('nombres','nombre'),
		'observation' 			=> array('observaciones','observación'),
		'part_no' 				=> array('no partes','no parte'),
		'password' 				=> array('contraseñas','contraseña'),
		'payment_method' 		=> array('metodos pago','metodo pago'),
		'phone' 				=> array('telefonos','telefono'),
		'picture' 				=> array('imagenes','imagen'),
		'plural_name' 			=> array('nombres plural','nombre plural'),
		'price' 				=> array('precios','precio'),
		'principal' 			=> array('principales','principal'),
		'product' 				=> array('productos','producto','image_path'=> 'public/images/product','file_path'=> 'public/files/product'),
		'qty_buy' 				=> array('cantidades comprar','cantidad comprar'),
		'qty_low' 				=> array('cantidades minimas','cantidad minima'),
		'receive_inventory'		=> array('entradas','entradas'),
		'register_date'			=> array('fechas de registro','fecha de registro'),
		'rol' 					=> array('roles','rol'),
		'serial_name' 			=> array('seriales','serial'),
		'shipment' 				=> array('trasportadoras','transportador'),
		'signature' 			=> array('firmas','firma'),
		'status'		 		=> array('estados','estado'),
		'shipping_cost' 		=> array('costos envio','costo envio'),
		'singular_name' 		=> array('nombres singular','nombre singular'),
		'specification' 		=> array('especificaciones','especificación','image_path'=> 'public/images/specification'),
		'specification_file'	=> array('archivos especificaciones','archivo especificación'),
		'specification_master' 	=> array('especificaciones maestras','espeficación maestra','image_path'=> 'public/images/specification_master'),
		'status' 				=> array('estados','estado'),
		'video' 				=> array('videos','video'),
		'user'					=> array('usuarios','usuario'),
		'username'				=> array('nombres usuario','nombre usuario'),
		'user_shortcut'			=> array('accesos directos usuario','acceso diercto usuario'),
		'user_type'				=> array('tipos de usuarios','tipo de usuario'),
		'upc_bar_code'			=> array('codigos UPC', 'codigo UPC'),
		'webpage'				=> array('paginas web', 'pagina web'),
		'zipcode'				=> array('zipcode', 'zipcode')
		)
);
?>