	<div class="navbar-default navbar-fixed-top navbar-inverse" role="navigation">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
				<span class="sr-only">Cambiar Navegación</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="#"><span class="fa fa-home"></span></a>
		</div>
		<div class="navbar-collapse collapse " id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav">
				<?php $moduleName = ""; ?>
				<?php foreach($resources as $module => $resource): ?>
					<?php foreach($resource as $resourceValue): ?>
						<?php if(array_search($resourceValue,$resourceAllowed)!==FALSE): ?>
							<?php if($moduleName!==$module): ?>
								<li class="dropdown">
									<a href="<?php echo $this->url('application'); ?>" class="dropdown-toggle" data-toggle="dropdown"><?php echo $components[$module][0]; ?> <b class="caret"></b></a>
									<ul class="dropdown-menu">
									<?php endif; ?>
									<li>
										<a href="<?php echo $this->url($module."/".$resourceValue); ?>" class='capitalize-text'><?php echo $components[$resourceValue][0] ; ?></a>
									</li>
								<?php endif; ?>
								<?php $moduleName = $module; ?>
							<?php endforeach; ?>
						</ul>
					</li>
				<?php endforeach; ?>
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i>
						<?php if(!empty($identity->first_name)) echo $identity->first_name; ?>
						<?php if(!empty($identity->last_name)) echo $identity->last_name; ?>
						<b class="caret"></b>
					</a>
					<ul class="dropdown-menu">
						<li><a href="#">Perfil</a></li>
						<li class="divider"></li>
						<li><a href="<?php echo $this->url("security/logout"); ?>">Cerrar Sesión</a></li>
					</ul>
				</li>
			</ul>
		</div>
	</div>