	<div class="navbar-default navbar-fixed-top navbar-inverse" role="navigation">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
				<span class="sr-only">Cambiar Navegación</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="#"><span class="glyphicon glyphicon-home"></span></a>
		</div>
		<div class="navbar-collapse collapse " id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav">
				<?php foreach($resources as $module => $resource): ?>
					<li class="dropdown">
						<a href="<?php echo $this->url('application'); ?>" class="dropdown-toggle" data-toggle="dropdown"><?php echo $components[$module][0]; ?> <b class="caret"></b></a>
						<ul class="dropdown-menu">
							<?php foreach($resource as $resourceIndex => $resourceValue): ?>
								<li><a href="<?php echo $this->url($module."/".$resourceIndex); ?>" class='capitalize-text'><?php echo $components[$resourceIndex][0] ; ?></a></li>
							<?php endforeach; ?>
						</ul>
					</li>
				<?php endforeach; ?>
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-user"></span>
						<?php if(!empty($identity->first_name)) echo $identity->first_name; ?>
						<?php if(!empty($identity->last_name)) echo $identity->last_name; ?>
						<b class="caret"></b>
					</a>
					<ul class="dropdown-menu">
						<li><a href="#">Perfil</a></li>
						<li><a href="#">Configuración</a></li>
						<li class="divider"></li>
						<li><a href="#">Ayudanos a mejorar</a></li>
						<li><a href="#">Reportar error</a></li>
						<li class="divider"></li>
						<li><a href="<?php echo $this->url("security/logout"); ?>">Cerrar Sesión</a></li>
					</ul>
				</li>
			</ul>
		</div>
	</div>